<?php

require_once(__DIR__ . '/notify.php');
require_once(__DIR__ . '/communication_targets.php');

function app_ensure_notifications_ai_schema(PDO $conn): void
{
	if (!app_table_exists($conn, 'tbl_notifications')) {
		return;
	}

	$columnSql = [
		'type' => "ALTER TABLE tbl_notifications ADD COLUMN type varchar(30) DEFAULT 'info'",
		'module_name' => "ALTER TABLE tbl_notifications ADD COLUMN module_name varchar(100) DEFAULT NULL",
		'user_role' => "ALTER TABLE tbl_notifications ADD COLUMN user_role varchar(50) DEFAULT NULL",
		'priority' => "ALTER TABLE tbl_notifications ADD COLUMN priority int DEFAULT 0",
		'source_key' => "ALTER TABLE tbl_notifications ADD COLUMN source_key varchar(190) DEFAULT NULL",
	];
	foreach ($columnSql as $column => $sql) {
		if (!app_column_exists($conn, 'tbl_notifications', $column)) {
			try {
				$conn->exec($sql);
			} catch (Throwable $e) {
				// best effort only
			}
		}
	}

	if (!app_table_exists($conn, 'tbl_notification_reads')) {
		try {
			if (DBDriver === 'pgsql') {
				$conn->exec("CREATE TABLE IF NOT EXISTS tbl_notification_reads (
					id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
					notification_id integer NOT NULL,
					actor_type varchar(20) NOT NULL,
					actor_id varchar(50) NOT NULL,
					read_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					PRIMARY KEY (id)
				)");
				$conn->exec("CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_reads_unique ON tbl_notification_reads (notification_id, actor_type, actor_id)");
			} else {
				$conn->exec("CREATE TABLE IF NOT EXISTS tbl_notification_reads (
					id int NOT NULL AUTO_INCREMENT,
					notification_id int NOT NULL,
					actor_type varchar(20) NOT NULL,
					actor_id varchar(50) NOT NULL,
					read_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					PRIMARY KEY (id),
					UNIQUE KEY idx_notification_reads_unique (notification_id, actor_type, actor_id)
				) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
			}
		} catch (Throwable $e) {
			// best effort only
		}
	}
}

function app_notification_actor_type_for_role(string $role): string
{
	$role = strtolower(trim($role));
	return in_array($role, ['student', 'parent'], true) ? $role : 'staff';
}

function app_notification_audiences_for_role(string $role): array
{
	$role = strtolower(trim($role));
	$map = [
		'admin' => ['all', 'staff', 'admin'],
		'academic' => ['all', 'staff', 'academic'],
		'teacher' => ['all', 'staff', 'teacher'],
		'accountant' => ['all', 'staff', 'accountant'],
		'bom' => ['all', 'staff', 'bom'],
		'student' => ['all', 'students', 'student'],
		'parent' => ['all', 'parents', 'parent'],
	];
	return $map[$role] ?? ['all'];
}

function app_system_notify_unique(PDO $conn, string $title, string $message, string $sourceKey, array $options = []): bool
{
	app_ensure_notifications_ai_schema($conn);
	if ($sourceKey === '' || !app_table_exists($conn, 'tbl_notifications')) {
		return app_system_notify($conn, $title, $message, $options);
	}

	try {
		if (app_column_exists($conn, 'tbl_notifications', 'source_key')) {
			$stmt = $conn->prepare("SELECT id FROM tbl_notifications WHERE source_key = ? LIMIT 1");
			$stmt->execute([$sourceKey]);
			$id = (int)$stmt->fetchColumn();
			if ($id > 0) {
				$fields = ['title = ?', 'message = ?'];
				$values = [$title, $message];
				if (app_column_exists($conn, 'tbl_notifications', 'type')) {
					$fields[] = 'type = ?';
					$values[] = (string)($options['type'] ?? 'info');
				}
				if (app_column_exists($conn, 'tbl_notifications', 'module_name')) {
					$fields[] = 'module_name = ?';
					$values[] = (string)($options['module_name'] ?? '');
				}
				if (app_column_exists($conn, 'tbl_notifications', 'user_role')) {
					$fields[] = 'user_role = ?';
					$values[] = (string)($options['user_role'] ?? '');
				}
				if (app_column_exists($conn, 'tbl_notifications', 'priority')) {
					$fields[] = 'priority = ?';
					$values[] = (int)($options['priority'] ?? 0);
				}
				$values[] = $id;
				$stmt = $conn->prepare("UPDATE tbl_notifications SET " . implode(', ', $fields) . " WHERE id = ?");
				return $stmt->execute($values);
			}
		}
	} catch (Throwable $e) {
		// continue to insert
	}

	$options['source_key'] = $sourceKey;
	return app_system_notify($conn, $title, $message, $options);
}

function app_system_notify(PDO $conn, string $title, string $message, array $options = []): bool
{
	if (!app_table_exists($conn, 'tbl_notifications')) {
		return false;
	}

	app_ensure_notifications_ai_schema($conn);

	$title = trim($title);
	$message = trim($message);
	if ($title === '' || $message === '') {
		return false;
	}

	$audience = trim((string)($options['audience'] ?? 'all'));
	if ($audience === '') {
		$audience = 'all';
	}
	$classId = isset($options['class_id']) ? (int)$options['class_id'] : null;
	$termId = isset($options['term_id']) ? (int)$options['term_id'] : null;
	$link = trim((string)($options['link'] ?? 'notifications'));
	$createdBy = isset($options['created_by']) ? (int)$options['created_by'] : null;
	$type = trim((string)($options['type'] ?? 'info'));
	$moduleName = trim((string)($options['module_name'] ?? ''));
	$userRole = trim((string)($options['user_role'] ?? ''));
	$priority = isset($options['priority']) ? (int)$options['priority'] : 0;
	$sourceKey = trim((string)($options['source_key'] ?? ''));

	$columns = ['title', 'message'];
	$values = [$title, $message];

	if (app_column_exists($conn, 'tbl_notifications', 'audience')) {
		$columns[] = 'audience';
		$values[] = $audience;
	}
	if (app_column_exists($conn, 'tbl_notifications', 'class_id')) {
		$columns[] = 'class_id';
		$values[] = $classId;
	}
	if (app_column_exists($conn, 'tbl_notifications', 'term_id')) {
		$columns[] = 'term_id';
		$values[] = $termId;
	}
	if (app_column_exists($conn, 'tbl_notifications', 'link')) {
		$columns[] = 'link';
		$values[] = $link;
	}
	if (app_column_exists($conn, 'tbl_notifications', 'created_by')) {
		$columns[] = 'created_by';
		$values[] = $createdBy;
	}
	if (app_column_exists($conn, 'tbl_notifications', 'type')) {
		$columns[] = 'type';
		$values[] = $type !== '' ? $type : 'info';
	}
	if (app_column_exists($conn, 'tbl_notifications', 'module_name')) {
		$columns[] = 'module_name';
		$values[] = $moduleName !== '' ? $moduleName : null;
	}
	if (app_column_exists($conn, 'tbl_notifications', 'user_role')) {
		$columns[] = 'user_role';
		$values[] = $userRole !== '' ? $userRole : null;
	}
	if (app_column_exists($conn, 'tbl_notifications', 'priority')) {
		$columns[] = 'priority';
		$values[] = $priority;
	}
	if (app_column_exists($conn, 'tbl_notifications', 'source_key')) {
		$columns[] = 'source_key';
		$values[] = $sourceKey !== '' ? $sourceKey : null;
	}

	$placeholders = implode(',', array_fill(0, count($columns), '?'));
	$sql = 'INSERT INTO tbl_notifications (' . implode(',', $columns) . ') VALUES (' . $placeholders . ')';
	$stmt = $conn->prepare($sql);
	$inserted = $stmt->execute($values);
	if ($inserted) {
		app_notification_send_email_delivery($conn, $title, $message, $options);
	}
	return $inserted;
}

function app_notification_email_enabled(PDO $conn): bool
{
	try {
		if (function_exists('app_setting_get')) {
			return app_setting_get($conn, 'notification_email_enabled', '1') !== '0';
		}
	} catch (Throwable $e) {
		// default to enabled
	}
	return true;
}

function app_notification_email_min_priority(PDO $conn): int
{
	try {
		if (function_exists('app_setting_get')) {
			$value = (int)app_setting_get($conn, 'notification_email_min_priority', '75');
			return max(0, min(100, $value));
		}
	} catch (Throwable $e) {
		// fall through
	}
	return 75;
}

function app_notification_should_send_email(PDO $conn, array $options = []): bool
{
	if (!app_notification_email_enabled($conn)) {
		return false;
	}

	if (!empty($options['force_email'])) {
		return true;
	}

	$priority = isset($options['priority']) ? (int)$options['priority'] : 0;
	return $priority >= app_notification_email_min_priority($conn);
}

function app_notification_recipient_email(string $value): string
{
	$value = strtolower(trim($value));
	return filter_var($value, FILTER_VALIDATE_EMAIL) ? $value : '';
}

function app_notification_add_recipient(array &$bucket, string $email, string $name = ''): void
{
	$email = app_notification_recipient_email($email);
	if ($email === '') {
		return;
	}
	if (!isset($bucket[$email])) {
		$bucket[$email] = [
			'email' => $email,
			'name' => trim($name),
		];
	}
}

function app_notification_collect_target_contacts(PDO $conn, string $targetType, string $targetValue = ''): array
{
	$rows = app_communication_targets($conn, $targetType, $targetValue);
	$contacts = [];
	foreach ($rows as $row) {
		app_notification_add_recipient($contacts, (string)($row['email'] ?? ''), (string)($row['name'] ?? ''));
	}
	return array_values($contacts);
}

function app_notification_collect_staff_role_contacts(PDO $conn, string $role): array
{
	$role = strtolower(trim($role));
	$levelMap = [
		'admin' => [0, 9],
		'academic' => [1],
		'teacher' => [2],
		'accountant' => [5],
		'bom' => [10],
	];
	if (!isset($levelMap[$role]) || !app_table_exists($conn, 'tbl_staff') || !app_column_exists($conn, 'tbl_staff', 'email')) {
		return [];
	}

	$levels = $levelMap[$role];
	$placeholders = implode(',', array_fill(0, count($levels), '?'));
	$sql = "SELECT id, CONCAT_WS(' ', fname, lname) AS name, email FROM tbl_staff WHERE level IN ($placeholders)";
	if (app_column_exists($conn, 'tbl_staff', 'status')) {
		$sql .= " AND COALESCE(status, 1) = 1";
	}
	$sql .= " ORDER BY fname, lname";

	$stmt = $conn->prepare($sql);
	$stmt->execute($levels);
	$contacts = [];
	foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $row) {
		app_notification_add_recipient($contacts, (string)($row['email'] ?? ''), (string)($row['name'] ?? ''));
	}
	return array_values($contacts);
}

function app_notification_email_recipients(PDO $conn, array $options = []): array
{
	$contacts = [];
	$targetsOnly = !empty($options['email_targets_only']);

	$emailTargets = $options['email_targets'] ?? [];
	if (is_array($emailTargets)) {
		foreach ($emailTargets as $target) {
			if (is_array($target)) {
				app_notification_add_recipient($contacts, (string)($target['email'] ?? ''), (string)($target['name'] ?? ''));
			} else {
				app_notification_add_recipient($contacts, (string)$target, '');
			}
		}
	}

	$recipientScope = trim((string)($options['recipient_scope'] ?? ''));
	if ($recipientScope !== '') {
		$scopeValue = trim((string)($options['recipient_scope_value'] ?? ''));
		foreach (app_notification_collect_target_contacts($conn, $recipientScope, $scopeValue) as $contact) {
			app_notification_add_recipient($contacts, (string)($contact['email'] ?? ''), (string)($contact['name'] ?? ''));
		}
	}

	$userRole = strtolower(trim((string)($options['user_role'] ?? '')));
	if ($userRole !== '') {
		foreach (app_notification_collect_staff_role_contacts($conn, $userRole) as $contact) {
			app_notification_add_recipient($contacts, (string)($contact['email'] ?? ''), (string)($contact['name'] ?? ''));
		}
	}

	if ($targetsOnly) {
		return array_values($contacts);
	}

	$audience = strtolower(trim((string)($options['audience'] ?? 'all')));
	$classId = isset($options['class_id']) ? (int)$options['class_id'] : 0;
	$hasRoleScopedStaff = in_array($userRole, ['admin', 'academic', 'teacher', 'accountant', 'bom'], true);

	$scopeMap = [
		'all' => ['all_staff', 'all_students', 'all_parents'],
		'staff' => ['all_staff'],
		'students' => ['all_students'],
		'student' => ['all_students'],
		'parents' => ['all_parents'],
		'parent' => ['all_parents'],
	];

	if ($audience === 'class' && $classId > 0) {
		foreach (['class_students', 'class_parents'] as $targetType) {
			foreach (app_notification_collect_target_contacts($conn, $targetType, (string)$classId) as $contact) {
				app_notification_add_recipient($contacts, (string)($contact['email'] ?? ''), (string)($contact['name'] ?? ''));
			}
		}
	} elseif (isset($scopeMap[$audience])) {
		foreach ($scopeMap[$audience] as $targetType) {
			if ($targetType === 'all_staff' && $hasRoleScopedStaff) {
				continue;
			}
			foreach (app_notification_collect_target_contacts($conn, $targetType, '') as $contact) {
				app_notification_add_recipient($contacts, (string)($contact['email'] ?? ''), (string)($contact['name'] ?? ''));
			}
		}
	}

	return array_values($contacts);
}

function app_notification_email_html(string $title, string $message, string $link = ''): string
{
	$appName = defined('APP_NAME') ? (string)APP_NAME : 'School Management System';
	$schoolName = defined('WBName') ? (string)WBName : $appName;
	$linkHtml = $link !== '' ? '<p style="margin:24px 0 0;"><a href="' . htmlspecialchars($link, ENT_QUOTES, 'UTF-8') . '" style="display:inline-block;background:#0f766e;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:600;">Open Notification</a></p>' : '';

	return '<div style="font-family:Arial,sans-serif;background:#f5f7fb;padding:24px;color:#1f2937;">'
		. '<div style="max-width:680px;margin:0 auto;background:#ffffff;border-radius:14px;padding:28px;border:1px solid #e5e7eb;">'
		. '<div style="font-size:12px;font-weight:700;letter-spacing:.12em;color:#0f766e;text-transform:uppercase;">' . htmlspecialchars($schoolName, ENT_QUOTES, 'UTF-8') . '</div>'
		. '<h2 style="margin:12px 0 16px;font-size:24px;line-height:1.3;color:#111827;">' . htmlspecialchars($title, ENT_QUOTES, 'UTF-8') . '</h2>'
		. '<div style="font-size:15px;line-height:1.7;color:#374151;white-space:pre-line;">' . nl2br(htmlspecialchars($message, ENT_QUOTES, 'UTF-8')) . '</div>'
		. $linkHtml
		. '<p style="margin:28px 0 0;font-size:12px;color:#6b7280;">Sent automatically from ' . htmlspecialchars($appName, ENT_QUOTES, 'UTF-8') . '.</p>'
		. '</div></div>';
}

function app_notification_send_email_delivery(PDO $conn, string $title, string $message, array $options = []): void
{
	if (!app_notification_should_send_email($conn, $options)) {
		return;
	}

	$recipients = app_notification_email_recipients($conn, $options);
	if (empty($recipients)) {
		return;
	}

	$subject = $title . ' - ' . (defined('WBName') ? (string)WBName : (defined('APP_NAME') ? (string)APP_NAME : 'School'));
	$link = trim((string)($options['email_link'] ?? ''));
	$html = app_notification_email_html($title, $message, $link);

	foreach ($recipients as $recipient) {
		$email = trim((string)($recipient['email'] ?? ''));
		if ($email === '') {
			continue;
		}
		try {
			app_send_email($conn, $email, $subject, $html);
		} catch (Throwable $e) {
			error_log('[system_notifications.email] ' . $e->getMessage());
		}
	}
}

function app_notification_mark_all_read(PDO $conn, string $actorType, string $actorId, array $notificationIds): void
{
	app_ensure_notifications_ai_schema($conn);
	if ($actorId === '' || empty($notificationIds) || !app_table_exists($conn, 'tbl_notification_reads')) {
		return;
	}
	$notificationIds = array_values(array_unique(array_filter(array_map('intval', $notificationIds))));
	foreach ($notificationIds as $notificationId) {
		try {
			if (DBDriver === 'pgsql') {
				$stmt = $conn->prepare("INSERT INTO tbl_notification_reads (notification_id, actor_type, actor_id) VALUES (?,?,?) ON CONFLICT DO NOTHING");
				$stmt->execute([$notificationId, $actorType, $actorId]);
			} else {
				$stmt = $conn->prepare("INSERT IGNORE INTO tbl_notification_reads (notification_id, actor_type, actor_id) VALUES (?,?,?)");
				$stmt->execute([$notificationId, $actorType, $actorId]);
			}
		} catch (Throwable $e) {
			// best effort only
		}
	}
}
