BEGIN;

-- Parents (for parent portal)
CREATE TABLE IF NOT EXISTS tbl_parents (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  fname varchar(70) NOT NULL,
  lname varchar(70) NOT NULL,
  phone varchar(30) NOT NULL DEFAULT '',
  email varchar(120) NOT NULL,
  password varchar(255) NOT NULL,
  status integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_parents_email_uq ON tbl_parents (email);

CREATE TABLE IF NOT EXISTS tbl_parent_students (
  parent_id integer NOT NULL,
  student_id varchar(20) NOT NULL,
  PRIMARY KEY (parent_id, student_id),
  CONSTRAINT tbl_parent_students_parent_fk FOREIGN KEY (parent_id) REFERENCES tbl_parents (id) ON DELETE CASCADE,
  CONSTRAINT tbl_parent_students_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE
);

-- Student attendance
CREATE TABLE IF NOT EXISTS tbl_attendance_sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  class_id integer NOT NULL,
  term_id integer NULL,
  session_date date NOT NULL,
  session_type varchar(20) NOT NULL DEFAULT 'daily', -- daily | period
  subject_id integer NULL,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_attendance_sessions_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_attendance_sessions_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE SET NULL,
  CONSTRAINT tbl_attendance_sessions_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE SET NULL,
  CONSTRAINT tbl_attendance_sessions_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_attendance_sessions_unique
  ON tbl_attendance_sessions (class_id, session_date, session_type, COALESCE(subject_id, 0));

CREATE TABLE IF NOT EXISTS tbl_attendance_records (
  session_id integer NOT NULL,
  student_id varchar(20) NOT NULL,
  status varchar(10) NOT NULL, -- present | absent | late | excused
  marked_by integer NULL,
  marked_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (session_id, student_id),
  CONSTRAINT tbl_attendance_records_session_fk FOREIGN KEY (session_id) REFERENCES tbl_attendance_sessions (id) ON DELETE CASCADE,
  CONSTRAINT tbl_attendance_records_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE,
  CONSTRAINT tbl_attendance_records_staff_fk FOREIGN KEY (marked_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

-- Staff attendance (basic clock in/out)
CREATE TABLE IF NOT EXISTS tbl_staff_attendance (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  staff_id integer NOT NULL,
  attendance_date date NOT NULL,
  status varchar(10) NOT NULL DEFAULT 'present',
  clock_in timestamp NULL,
  clock_out timestamp NULL,
  marked_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_staff_attendance_staff_fk FOREIGN KEY (staff_id) REFERENCES tbl_staff (id) ON DELETE CASCADE,
  CONSTRAINT tbl_staff_attendance_marked_by_fk FOREIGN KEY (marked_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_staff_attendance_unique
  ON tbl_staff_attendance (staff_id, attendance_date);

-- Audit log (security)
CREATE TABLE IF NOT EXISTS tbl_audit_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  actor_type varchar(20) NOT NULL, -- staff | student | parent
  actor_id varchar(50) NOT NULL,
  action varchar(100) NOT NULL,
  entity varchar(100) NOT NULL,
  entity_id varchar(100) NOT NULL DEFAULT '',
  ip varchar(90) NOT NULL DEFAULT '',
  user_agent text NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMIT;

