BEGIN;

-- Fee items (Tuition, Transport, Exams, etc.)
CREATE TABLE IF NOT EXISTS tbl_fee_items (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(120) NOT NULL,
  description text NOT NULL DEFAULT '',
  status integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_fee_items_name_uq ON tbl_fee_items (name);

-- Fee structure: per class + term + item
CREATE TABLE IF NOT EXISTS tbl_fee_structures (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  class_id integer NOT NULL,
  term_id integer NOT NULL,
  item_id integer NOT NULL,
  amount numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_fee_structures_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_fee_structures_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_fee_structures_item_fk FOREIGN KEY (item_id) REFERENCES tbl_fee_items (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_fee_structures_unique
  ON tbl_fee_structures (class_id, term_id, item_id);

-- Invoice header
CREATE TABLE IF NOT EXISTS tbl_invoices (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id varchar(20) NOT NULL,
  class_id integer NOT NULL,
  term_id integer NOT NULL,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date NULL,
  status varchar(20) NOT NULL DEFAULT 'open', -- open | paid | void
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_invoices_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE,
  CONSTRAINT tbl_invoices_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_invoices_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_invoices_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_invoices_unique
  ON tbl_invoices (student_id, term_id);

-- Invoice lines
CREATE TABLE IF NOT EXISTS tbl_invoice_lines (
  invoice_id integer NOT NULL,
  item_id integer NOT NULL,
  amount numeric(12,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (invoice_id, item_id),
  CONSTRAINT tbl_invoice_lines_invoice_fk FOREIGN KEY (invoice_id) REFERENCES tbl_invoices (id) ON DELETE CASCADE,
  CONSTRAINT tbl_invoice_lines_item_fk FOREIGN KEY (item_id) REFERENCES tbl_fee_items (id) ON DELETE RESTRICT
);

-- Payments (manual for now)
CREATE TABLE IF NOT EXISTS tbl_payments (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  invoice_id integer NOT NULL,
  amount numeric(12,2) NOT NULL DEFAULT 0,
  method varchar(50) NOT NULL DEFAULT 'cash', -- cash | mpesa | bank | card | other
  reference varchar(120) NOT NULL DEFAULT '',
  paid_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  received_by integer NULL,
  PRIMARY KEY (id),
  CONSTRAINT tbl_payments_invoice_fk FOREIGN KEY (invoice_id) REFERENCES tbl_invoices (id) ON DELETE CASCADE,
  CONSTRAINT tbl_payments_staff_fk FOREIGN KEY (received_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_payments_invoice_idx ON tbl_payments (invoice_id);

COMMIT;

