BEGIN;

CREATE TABLE IF NOT EXISTS tbl_exam_schedule (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  term_id integer NOT NULL,
  class_id integer NOT NULL,
  subject_combination_id integer NOT NULL,
  exam_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  room varchar(60) NOT NULL DEFAULT '',
  invigilator integer NULL,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_exam_schedule_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exam_schedule_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exam_schedule_comb_fk FOREIGN KEY (subject_combination_id) REFERENCES tbl_subject_combinations (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exam_schedule_inv_fk FOREIGN KEY (invigilator) REFERENCES tbl_staff (id) ON DELETE SET NULL,
  CONSTRAINT tbl_exam_schedule_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_exam_schedule_term_idx ON tbl_exam_schedule (term_id);
CREATE INDEX IF NOT EXISTS tbl_exam_schedule_class_idx ON tbl_exam_schedule (class_id);
CREATE INDEX IF NOT EXISTS tbl_exam_schedule_date_idx ON tbl_exam_schedule (exam_date);

COMMIT;

