BEGIN;

-- Store M-Pesa API settings (prefer env vars in production; DB is optional fallback)
CREATE TABLE IF NOT EXISTS tbl_payment_settings (
  id integer NOT NULL,
  provider varchar(30) NOT NULL DEFAULT 'mpesa',
  environment varchar(20) NOT NULL DEFAULT 'sandbox', -- sandbox | live
  shortcode varchar(20) NOT NULL DEFAULT '',
  passkey varchar(255) NOT NULL DEFAULT '',
  consumer_key varchar(255) NOT NULL DEFAULT '',
  consumer_secret varchar(255) NOT NULL DEFAULT '',
  callback_url varchar(255) NOT NULL DEFAULT '',
  enabled integer NOT NULL DEFAULT 0,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO tbl_payment_settings (id, provider, environment, enabled)
VALUES (1, 'mpesa', 'sandbox', 0)
ON CONFLICT (id) DO NOTHING;

-- Track STK push requests per invoice
CREATE TABLE IF NOT EXISTS tbl_mpesa_stk_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  invoice_id integer NOT NULL,
  phone varchar(30) NOT NULL,
  amount numeric(12,2) NOT NULL DEFAULT 0,
  account_reference varchar(60) NOT NULL DEFAULT '',
  status varchar(20) NOT NULL DEFAULT 'pending', -- pending | sent | success | failed
  merchant_request_id varchar(80) NOT NULL DEFAULT '',
  checkout_request_id varchar(80) NOT NULL DEFAULT '',
  response_code varchar(20) NOT NULL DEFAULT '',
  response_desc varchar(255) NOT NULL DEFAULT '',
  customer_message varchar(255) NOT NULL DEFAULT '',
  result_code integer NULL,
  result_desc varchar(255) NOT NULL DEFAULT '',
  mpesa_receipt varchar(60) NOT NULL DEFAULT '',
  raw_callback text NOT NULL DEFAULT '',
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_mpesa_stk_requests_invoice_fk FOREIGN KEY (invoice_id) REFERENCES tbl_invoices (id) ON DELETE CASCADE,
  CONSTRAINT tbl_mpesa_stk_requests_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_mpesa_stk_requests_invoice_idx ON tbl_mpesa_stk_requests (invoice_id);
CREATE INDEX IF NOT EXISTS tbl_mpesa_stk_requests_checkout_idx ON tbl_mpesa_stk_requests (checkout_request_id);

COMMIT;

