BEGIN;

CREATE TABLE IF NOT EXISTS tbl_exam_types (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(90) NOT NULL,
  status integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_exam_types_name_uq ON tbl_exam_types (name);

CREATE TABLE IF NOT EXISTS tbl_exams (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(120) NOT NULL,
  term_id integer NOT NULL,
  class_id integer NOT NULL,
  exam_type_id integer NULL,
  status varchar(20) NOT NULL DEFAULT 'open',
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_exams_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exams_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exams_type_fk FOREIGN KEY (exam_type_id) REFERENCES tbl_exam_types (id) ON DELETE SET NULL,
  CONSTRAINT tbl_exams_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_subject_weights (
  subject_id integer NOT NULL,
  weight numeric(5,2) NOT NULL DEFAULT 1,
  PRIMARY KEY (subject_id),
  CONSTRAINT tbl_subject_weights_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_result_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  best_of integer NOT NULL DEFAULT 0,
  use_weights integer NOT NULL DEFAULT 1,
  require_fees_clear integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_report_cards (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id varchar(20) NOT NULL,
  class_id integer NOT NULL,
  term_id integer NOT NULL,
  total numeric(12,2) NOT NULL DEFAULT 0,
  mean numeric(6,2) NOT NULL DEFAULT 0,
  grade varchar(10) NOT NULL DEFAULT '',
  remark varchar(120) NOT NULL DEFAULT '',
  position integer NOT NULL DEFAULT 0,
  total_students integer NOT NULL DEFAULT 0,
  trend varchar(20) NOT NULL DEFAULT 'New',
  verification_code varchar(60) NOT NULL,
  report_hash varchar(120) NOT NULL,
  generated_by integer NULL,
  generated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  downloads integer NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT tbl_report_cards_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE,
  CONSTRAINT tbl_report_cards_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_report_cards_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_report_cards_staff_fk FOREIGN KEY (generated_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_report_cards_unique
  ON tbl_report_cards (student_id, term_id);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_report_cards_code_uq
  ON tbl_report_cards (verification_code);

CREATE TABLE IF NOT EXISTS tbl_report_card_subjects (
  report_id integer NOT NULL,
  subject_id integer NOT NULL,
  score numeric(6,2) NOT NULL DEFAULT 0,
  grade varchar(10) NOT NULL DEFAULT '',
  weight numeric(5,2) NOT NULL DEFAULT 1,
  teacher_id integer NULL,
  PRIMARY KEY (report_id, subject_id),
  CONSTRAINT tbl_report_card_subjects_report_fk FOREIGN KEY (report_id) REFERENCES tbl_report_cards (id) ON DELETE CASCADE,
  CONSTRAINT tbl_report_card_subjects_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE CASCADE,
  CONSTRAINT tbl_report_card_subjects_teacher_fk FOREIGN KEY (teacher_id) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

COMMIT;
