BEGIN;

CREATE TABLE IF NOT EXISTS tbl_notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title varchar(120) NOT NULL,
  message text NOT NULL,
  audience varchar(30) NOT NULL DEFAULT 'all', -- all | students | parents | staff | class
  class_id integer NULL,
  term_id integer NULL,
  link varchar(255) NOT NULL DEFAULT '',
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_notifications_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE SET NULL,
  CONSTRAINT tbl_notifications_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE SET NULL,
  CONSTRAINT tbl_notifications_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_notifications_audience_idx ON tbl_notifications (audience);
CREATE INDEX IF NOT EXISTS tbl_notifications_class_idx ON tbl_notifications (class_id);
CREATE INDEX IF NOT EXISTS tbl_notifications_created_at_idx ON tbl_notifications (created_at);

COMMIT;
