BEGIN;

CREATE TABLE IF NOT EXISTS tbl_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sender_type varchar(20) NOT NULL, -- admin | staff | teacher | parent | student
  sender_id varchar(50) NOT NULL,
  recipient_type varchar(20) NOT NULL, -- staff | teacher | parent | student
  recipient_id varchar(50) NOT NULL,
  subject varchar(120) NOT NULL DEFAULT '',
  body text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at timestamp NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS tbl_messages_recipient_idx ON tbl_messages (recipient_type, recipient_id);
CREATE INDEX IF NOT EXISTS tbl_messages_sender_idx ON tbl_messages (sender_type, sender_id);

CREATE TABLE IF NOT EXISTS tbl_sms_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recipient varchar(50) NOT NULL,
  message text NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'queued',
  provider varchar(50) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_email_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recipient varchar(120) NOT NULL,
  subject varchar(150) NOT NULL,
  message text NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'queued',
  provider varchar(50) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMIT;
