BEGIN;

CREATE TABLE IF NOT EXISTS tbl_library_books (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  isbn varchar(40) NOT NULL DEFAULT '',
  title varchar(150) NOT NULL,
  author varchar(120) NOT NULL DEFAULT '',
  category varchar(120) NOT NULL DEFAULT '',
  copies integer NOT NULL DEFAULT 1,
  available integer NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_library_loans (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  book_id integer NOT NULL,
  borrower_type varchar(20) NOT NULL, -- student | staff
  borrower_id varchar(50) NOT NULL,
  issued_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  due_at timestamp NULL,
  returned_at timestamp NULL,
  PRIMARY KEY (id),
  CONSTRAINT tbl_library_loans_book_fk FOREIGN KEY (book_id) REFERENCES tbl_library_books (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS tbl_library_loans_borrower_idx ON tbl_library_loans (borrower_type, borrower_id);

CREATE TABLE IF NOT EXISTS tbl_assets (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(150) NOT NULL,
  category varchar(120) NOT NULL DEFAULT '',
  quantity integer NOT NULL DEFAULT 0,
  location varchar(120) NOT NULL DEFAULT '',
  status varchar(40) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_asset_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  asset_id integer NOT NULL,
  action varchar(50) NOT NULL, -- add | issue | return | update | dispose
  quantity integer NOT NULL DEFAULT 0,
  note text NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_asset_logs_asset_fk FOREIGN KEY (asset_id) REFERENCES tbl_assets (id) ON DELETE CASCADE
);

COMMIT;
