BEGIN;

CREATE TABLE IF NOT EXISTS tbl_vehicles (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  plate_number varchar(30) NOT NULL,
  model varchar(80) NOT NULL DEFAULT '',
  capacity integer NOT NULL DEFAULT 0,
  driver_id integer NULL,
  status varchar(30) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_vehicles_driver_fk FOREIGN KEY (driver_id) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_routes (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(120) NOT NULL,
  vehicle_id integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_routes_vehicle_fk FOREIGN KEY (vehicle_id) REFERENCES tbl_vehicles (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_route_stops (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  route_id integer NOT NULL,
  stop_name varchar(120) NOT NULL,
  stop_order integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  CONSTRAINT tbl_route_stops_route_fk FOREIGN KEY (route_id) REFERENCES tbl_routes (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_transport_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id varchar(50) NOT NULL,
  route_id integer NOT NULL,
  stop_id integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_transport_assignments_route_fk FOREIGN KEY (route_id) REFERENCES tbl_routes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_transport_assignments_stop_fk FOREIGN KEY (stop_id) REFERENCES tbl_route_stops (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_transport_assignments_student_idx ON tbl_transport_assignments (student_id);

COMMIT;
