BEGIN;

CREATE TABLE IF NOT EXISTS tbl_roles (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(60) NOT NULL,
  level integer NOT NULL DEFAULT 0,
  description text NOT NULL DEFAULT '',
  is_system boolean NOT NULL DEFAULT true,
  PRIMARY KEY (id),
  UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tbl_permissions (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code varchar(80) NOT NULL,
  description text NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS tbl_role_permissions (
  role_id integer NOT NULL,
  permission_id integer NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT tbl_role_permissions_role_fk FOREIGN KEY (role_id) REFERENCES tbl_roles (id) ON DELETE CASCADE,
  CONSTRAINT tbl_role_permissions_perm_fk FOREIGN KEY (permission_id) REFERENCES tbl_permissions (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_user_roles (
  staff_id integer NOT NULL,
  role_id integer NOT NULL,
  PRIMARY KEY (staff_id, role_id),
  CONSTRAINT tbl_user_roles_staff_fk FOREIGN KEY (staff_id) REFERENCES tbl_staff (id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_roles_role_fk FOREIGN KEY (role_id) REFERENCES tbl_roles (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_module_locks (
  module varchar(60) NOT NULL,
  locked boolean NOT NULL DEFAULT false,
  reason text NOT NULL DEFAULT '',
  locked_by integer NULL,
  locked_at timestamp NULL,
  PRIMARY KEY (module),
  CONSTRAINT tbl_module_locks_staff_fk FOREIGN KEY (locked_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

INSERT INTO tbl_permissions (code, description) VALUES
('system.manage', 'Manage system settings'),
('audit.view', 'View audit logs'),
('students.manage', 'Manage students'),
('staff.manage', 'Manage staff'),
('attendance.manage', 'Manage attendance'),
('exams.manage', 'Manage exams and timetable'),
('marks.enter', 'Enter marks and assessments'),
('results.approve', 'Approve results'),
('results.lock', 'Lock results'),
('results.unlock', 'Unlock results'),
('report.generate', 'Generate report cards'),
('report.view', 'View report cards'),
('finance.manage', 'Manage fees and payments'),
('finance.view', 'View finance reports'),
('communication.manage', 'Manage communication'),
('transport.manage', 'Manage transport'),
('library.manage', 'Manage library'),
('inventory.manage', 'Manage inventory')
ON CONFLICT (code) DO NOTHING;

INSERT INTO tbl_roles (name, level, description, is_system) VALUES
('Super Admin', 9, 'System owner with full control', true),
('School Admin', 0, 'School-level administrator', true),
('Teacher', 2, 'Teacher role', true),
('Accountant', 5, 'Finance officer', true),
('HR Manager', 6, 'HR & payroll manager', true),
('Transport Manager', 7, 'Transport manager', true),
('Librarian', 8, 'Library manager', true)
ON CONFLICT (name) DO NOTHING;

-- Role permissions (id lookup by code/name).
INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM tbl_roles r JOIN tbl_permissions p ON p.code IN (
	'system.manage','audit.view','students.manage','staff.manage','attendance.manage','exams.manage',
	'marks.enter','results.approve','results.lock','results.unlock','report.generate','report.view',
	'finance.manage','finance.view','communication.manage','transport.manage','library.manage','inventory.manage'
) WHERE r.name = 'Super Admin'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM tbl_roles r JOIN tbl_permissions p ON p.code IN (
	'system.manage','audit.view','students.manage','staff.manage','attendance.manage','exams.manage',
	'results.approve','results.lock','report.generate','report.view','finance.manage','finance.view',
	'communication.manage','transport.manage','library.manage','inventory.manage'
) WHERE r.name = 'School Admin'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM tbl_roles r JOIN tbl_permissions p ON p.code IN (
	'attendance.manage','marks.enter','report.view'
) WHERE r.name = 'Teacher'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM tbl_roles r JOIN tbl_permissions p ON p.code IN (
	'finance.manage','finance.view'
) WHERE r.name = 'Accountant'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM tbl_roles r JOIN tbl_permissions p ON p.code IN (
	'staff.manage'
) WHERE r.name = 'HR Manager'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM tbl_roles r JOIN tbl_permissions p ON p.code IN (
	'transport.manage'
) WHERE r.name = 'Transport Manager'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM tbl_roles r JOIN tbl_permissions p ON p.code IN (
	'library.manage'
) WHERE r.name = 'Librarian'
ON CONFLICT DO NOTHING;

COMMIT;
