BEGIN;

CREATE TABLE IF NOT EXISTS tbl_cbc_assessments (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id varchar(50) NOT NULL,
  class_id integer NOT NULL,
  term_id integer NOT NULL,
  learning_area varchar(120) NOT NULL,
  strand varchar(120) NOT NULL DEFAULT '',
  level varchar(5) NOT NULL, -- EE | ME | AE | BE
  teacher_id integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS tbl_cbc_assessments_student_idx ON tbl_cbc_assessments (student_id);
CREATE INDEX IF NOT EXISTS tbl_cbc_assessments_term_idx ON tbl_cbc_assessments (term_id);

CREATE TABLE IF NOT EXISTS tbl_import_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  import_type varchar(60) NOT NULL,
  total integer NOT NULL DEFAULT 0,
  success integer NOT NULL DEFAULT 0,
  failed integer NOT NULL DEFAULT 0,
  details text NOT NULL DEFAULT '',
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_import_logs_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

COMMIT;
