BEGIN;

ALTER TABLE tbl_cbc_assessments
  ADD COLUMN IF NOT EXISTS subject_id integer NULL,
  ADD COLUMN IF NOT EXISTS marks numeric(6,2) NULL,
  ADD COLUMN IF NOT EXISTS points integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS updated_at timestamp NULL;

CREATE TABLE IF NOT EXISTS tbl_cbc_strands (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  subject_id integer NOT NULL,
  name varchar(120) NOT NULL,
  status integer NOT NULL DEFAULT 1,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_cbc_strands_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE CASCADE,
  CONSTRAINT tbl_cbc_strands_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_cbc_strands_unique ON tbl_cbc_strands (subject_id, name);
CREATE INDEX IF NOT EXISTS tbl_cbc_strands_subject_idx ON tbl_cbc_strands (subject_id);

COMMIT;
