BEGIN;

CREATE TABLE IF NOT EXISTS tbl_cbc_grading (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  level varchar(10) NOT NULL,
  min_mark numeric(6,2) NOT NULL DEFAULT 0,
  max_mark numeric(6,2) NOT NULL DEFAULT 100,
  points integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS tbl_cbc_grading_active_idx ON tbl_cbc_grading (active, sort_order);

INSERT INTO tbl_cbc_grading (level, min_mark, max_mark, points, sort_order)
SELECT v.level, v.min_mark, v.max_mark, v.points, v.sort_order
FROM (
  VALUES
    ('EE1', 90, 100, 8, 1),
    ('EE2', 75, 89, 7, 2),
    ('ME1', 58, 74, 6, 3),
    ('ME2', 41, 57, 5, 4),
    ('AE1', 31, 40, 4, 5),
    ('AE2', 21, 30, 3, 6),
    ('BE1', 11, 20, 2, 7),
    ('BE2', 1, 10, 1, 8),
    ('BE2', 0, 0, 0, 9)
) AS v(level, min_mark, max_mark, points, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM tbl_cbc_grading);

COMMIT;
