BEGIN;

CREATE TABLE IF NOT EXISTS tbl_validation_issues (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  issue_type varchar(50) NOT NULL,
  severity varchar(20) NOT NULL DEFAULT 'medium',
  message text NOT NULL,
  student_id varchar(20) NULL,
  class_id integer NULL,
  term_id integer NULL,
  subject_id integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_validation_issues_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE SET NULL,
  CONSTRAINT tbl_validation_issues_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE SET NULL,
  CONSTRAINT tbl_validation_issues_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE SET NULL,
  CONSTRAINT tbl_validation_issues_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_validation_issues_class_idx ON tbl_validation_issues (class_id, term_id);
CREATE INDEX IF NOT EXISTS tbl_validation_issues_student_idx ON tbl_validation_issues (student_id);

CREATE TABLE IF NOT EXISTS tbl_insights_alerts (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  alert_type varchar(50) NOT NULL,
  severity varchar(20) NOT NULL DEFAULT 'medium',
  title varchar(160) NOT NULL,
  message text NOT NULL,
  student_id varchar(20) NULL,
  class_id integer NULL,
  term_id integer NULL,
  subject_id integer NULL,
  status varchar(20) NOT NULL DEFAULT 'new',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_insights_alerts_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE SET NULL,
  CONSTRAINT tbl_insights_alerts_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE SET NULL,
  CONSTRAINT tbl_insights_alerts_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE SET NULL,
  CONSTRAINT tbl_insights_alerts_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_insights_alerts_status_idx ON tbl_insights_alerts (status, created_at);
CREATE INDEX IF NOT EXISTS tbl_insights_alerts_class_idx ON tbl_insights_alerts (class_id, term_id);
CREATE INDEX IF NOT EXISTS tbl_insights_alerts_student_idx ON tbl_insights_alerts (student_id);

COMMIT;
