BEGIN;

CREATE TABLE IF NOT EXISTS tbl_sms_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  provider varchar(80) NOT NULL DEFAULT 'custom',
  api_url varchar(255) NOT NULL DEFAULT '',
  api_key varchar(200) NOT NULL DEFAULT '',
  sender_id varchar(60) NOT NULL DEFAULT '',
  status integer NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO tbl_sms_settings (provider, api_url, api_key, sender_id, status)
SELECT 'custom', '', '', '', 0
WHERE NOT EXISTS (SELECT 1 FROM tbl_sms_settings);

COMMIT;
