BEGIN;

CREATE TABLE IF NOT EXISTS tbl_exam_mark_submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  exam_id integer NOT NULL,
  class_id integer NOT NULL,
  term_id integer NOT NULL,
  subject_combination_id integer NOT NULL,
  teacher_id integer NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'draft',
  submitted_at timestamp NULL,
  reviewed_at timestamp NULL,
  reviewed_by integer NULL,
  review_note varchar(255) NULL,
  PRIMARY KEY (id),
  CONSTRAINT tbl_exam_mark_submissions_exam_fk FOREIGN KEY (exam_id) REFERENCES tbl_exams (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exam_mark_submissions_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exam_mark_submissions_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exam_mark_submissions_subject_fk FOREIGN KEY (subject_combination_id) REFERENCES tbl_subject_combinations (id) ON DELETE CASCADE,
  CONSTRAINT tbl_exam_mark_submissions_teacher_fk FOREIGN KEY (teacher_id) REFERENCES tbl_staff (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_exam_mark_submissions_uq
  ON tbl_exam_mark_submissions (exam_id, subject_combination_id);

CREATE TABLE IF NOT EXISTS tbl_cbc_mark_submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  term_id integer NOT NULL,
  class_id integer NOT NULL,
  subject_id integer NOT NULL,
  subject_combination_id integer NOT NULL,
  teacher_id integer NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'draft',
  submitted_at timestamp NULL,
  reviewed_at timestamp NULL,
  reviewed_by integer NULL,
  review_note varchar(255) NULL,
  PRIMARY KEY (id),
  CONSTRAINT tbl_cbc_mark_submissions_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_cbc_mark_submissions_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_cbc_mark_submissions_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE CASCADE,
  CONSTRAINT tbl_cbc_mark_submissions_subjectcomb_fk FOREIGN KEY (subject_combination_id) REFERENCES tbl_subject_combinations (id) ON DELETE CASCADE,
  CONSTRAINT tbl_cbc_mark_submissions_teacher_fk FOREIGN KEY (teacher_id) REFERENCES tbl_staff (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_cbc_mark_submissions_uq
  ON tbl_cbc_mark_submissions (term_id, class_id, subject_combination_id);

COMMIT;
