BEGIN;

CREATE TABLE IF NOT EXISTS tbl_courses (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(120) NOT NULL,
  class_id integer NOT NULL,
  subject_id integer NOT NULL,
  teacher_id integer NOT NULL,
  status integer NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_courses_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_courses_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE CASCADE,
  CONSTRAINT tbl_courses_teacher_fk FOREIGN KEY (teacher_id) REFERENCES tbl_staff (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_lessons (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id integer NOT NULL,
  title varchar(150) NOT NULL,
  strand varchar(120) DEFAULT '',
  sub_strand varchar(120) DEFAULT '',
  competency varchar(180) DEFAULT '',
  description text DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_lessons_course_fk FOREIGN KEY (course_id) REFERENCES tbl_courses (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_lesson_content (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lesson_id integer NOT NULL,
  content_type varchar(30) NOT NULL, -- file | link | video
  file_path varchar(255) DEFAULT '',
  url varchar(255) DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_lesson_content_lesson_fk FOREIGN KEY (lesson_id) REFERENCES tbl_lessons (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id integer NOT NULL,
  lesson_id integer NULL,
  title varchar(150) NOT NULL,
  instructions text NOT NULL,
  due_date timestamp NULL,
  attachment varchar(255) DEFAULT '',
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_assignments_course_fk FOREIGN KEY (course_id) REFERENCES tbl_courses (id) ON DELETE CASCADE,
  CONSTRAINT tbl_assignments_lesson_fk FOREIGN KEY (lesson_id) REFERENCES tbl_lessons (id) ON DELETE SET NULL,
  CONSTRAINT tbl_assignments_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_assignment_submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  assignment_id integer NOT NULL,
  student_id varchar(20) NOT NULL,
  submission_text text DEFAULT '',
  file_path varchar(255) DEFAULT '',
  submitted_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  score numeric(6,2) DEFAULT 0,
  feedback text DEFAULT '',
  PRIMARY KEY (id),
  CONSTRAINT tbl_assignment_submissions_assignment_fk FOREIGN KEY (assignment_id) REFERENCES tbl_assignments (id) ON DELETE CASCADE,
  CONSTRAINT tbl_assignment_submissions_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_assignment_submissions_uq
  ON tbl_assignment_submissions (assignment_id, student_id);

CREATE TABLE IF NOT EXISTS tbl_quizzes (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id integer NOT NULL,
  title varchar(150) NOT NULL,
  total_marks numeric(6,2) DEFAULT 0,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_quizzes_course_fk FOREIGN KEY (course_id) REFERENCES tbl_courses (id) ON DELETE CASCADE,
  CONSTRAINT tbl_quizzes_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_quiz_questions (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  quiz_id integer NOT NULL,
  question text NOT NULL,
  qtype varchar(20) NOT NULL DEFAULT 'mcq',
  options text DEFAULT '',
  correct_answer text DEFAULT '',
  marks numeric(6,2) DEFAULT 1,
  PRIMARY KEY (id),
  CONSTRAINT tbl_quiz_questions_quiz_fk FOREIGN KEY (quiz_id) REFERENCES tbl_quizzes (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_quiz_results (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  quiz_id integer NOT NULL,
  student_id varchar(20) NOT NULL,
  score numeric(6,2) DEFAULT 0,
  submitted_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_quiz_results_quiz_fk FOREIGN KEY (quiz_id) REFERENCES tbl_quizzes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_quiz_results_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_quiz_results_uq
  ON tbl_quiz_results (quiz_id, student_id);

CREATE TABLE IF NOT EXISTS tbl_live_classes (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id integer NOT NULL,
  title varchar(150) NOT NULL,
  meeting_link varchar(255) NOT NULL,
  platform varchar(50) NOT NULL DEFAULT 'Meet',
  start_time timestamp NOT NULL,
  end_time timestamp NULL,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_live_classes_course_fk FOREIGN KEY (course_id) REFERENCES tbl_courses (id) ON DELETE CASCADE,
  CONSTRAINT tbl_live_classes_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_attendance_elearning (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  live_class_id integer NOT NULL,
  student_id varchar(20) NOT NULL,
  joined_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_attendance_elearning_class_fk FOREIGN KEY (live_class_id) REFERENCES tbl_live_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_attendance_elearning_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE
);

COMMIT;
