BEGIN;

CREATE TABLE IF NOT EXISTS tbl_ai_feedback (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  actor_type varchar(20) NOT NULL,
  actor_id varchar(50) NOT NULL,
  category varchar(30) NOT NULL DEFAULT 'feedback', -- ai | feedback
  message text NOT NULL,
  ai_response text DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMIT;
