BEGIN;

CREATE TABLE IF NOT EXISTS tbl_ai_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  actor_type varchar(20) NOT NULL,
  actor_id varchar(50) NOT NULL,
  role varchar(20) NOT NULL,
  question text NOT NULL,
  response text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_ai_queries (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  actor_type varchar(20) NOT NULL,
  actor_id varchar(50) NOT NULL,
  role varchar(20) NOT NULL,
  question text NOT NULL,
  intent varchar(50) NOT NULL DEFAULT 'general',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_ai_recommendations (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id varchar(20) NOT NULL,
  recommendation text NOT NULL,
  category varchar(30) NOT NULL DEFAULT 'academic',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_ai_recommendations_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE
);

COMMIT;
