BEGIN;

CREATE TABLE IF NOT EXISTS tbl_teacher_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  teacher_id integer NOT NULL,
  class_id integer NOT NULL,
  subject_id integer NOT NULL,
  term_id integer NOT NULL,
  year integer NOT NULL,
  status integer NOT NULL DEFAULT 1,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_teacher_assignments_teacher_fk FOREIGN KEY (teacher_id) REFERENCES tbl_staff (id) ON DELETE CASCADE,
  CONSTRAINT tbl_teacher_assignments_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_teacher_assignments_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE CASCADE,
  CONSTRAINT tbl_teacher_assignments_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_teacher_assignments_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_teacher_assignments_unique
  ON tbl_teacher_assignments (teacher_id, class_id, subject_id, term_id, year);

CREATE INDEX IF NOT EXISTS tbl_teacher_assignments_teacher_idx
  ON tbl_teacher_assignments (teacher_id);

COMMIT;
