BEGIN;

CREATE TABLE IF NOT EXISTS tbl_grading_systems (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(120) NOT NULL,
  type varchar(20) NOT NULL DEFAULT 'marks',
  description text NULL,
  is_default integer NOT NULL DEFAULT 0,
  is_active integer NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_grading_scales (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  grading_system_id integer NOT NULL,
  min_score numeric(6,2) NOT NULL,
  max_score numeric(6,2) NOT NULL,
  grade varchar(30) NOT NULL,
  points numeric(6,2) NOT NULL DEFAULT 0,
  remark varchar(255) NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active integer NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_grading_scales_system_fk FOREIGN KEY (grading_system_id) REFERENCES tbl_grading_systems (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS tbl_grading_scales_system_idx
  ON tbl_grading_scales (grading_system_id, is_active, sort_order);

ALTER TABLE tbl_exams
  ADD COLUMN IF NOT EXISTS grading_system_id integer NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'tbl_exams_grading_system_fk'
      AND table_name = 'tbl_exams'
  ) THEN
    ALTER TABLE tbl_exams
      ADD CONSTRAINT tbl_exams_grading_system_fk
      FOREIGN KEY (grading_system_id) REFERENCES tbl_grading_systems (id) ON DELETE SET NULL;
  END IF;
END $$;

ALTER TABLE tbl_exam_results
  ADD COLUMN IF NOT EXISTS grade_label varchar(30) NULL;

ALTER TABLE tbl_exam_results
  ADD COLUMN IF NOT EXISTS grade_points numeric(6,2) NULL;

CREATE TABLE IF NOT EXISTS tbl_app_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  setting_key varchar(100) NOT NULL,
  setting_value text NULL,
  updated_by integer NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_app_settings_key_unique UNIQUE (setting_key),
  CONSTRAINT tbl_app_settings_staff_fk FOREIGN KEY (updated_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_school_timetable (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  term_id integer NOT NULL,
  class_id integer NOT NULL,
  subject_id integer NOT NULL,
  teacher_id integer NOT NULL,
  day_name varchar(20) NOT NULL,
  session_label varchar(50) NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  room varchar(100) NULL,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_school_timetable_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE CASCADE,
  CONSTRAINT tbl_school_timetable_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE CASCADE,
  CONSTRAINT tbl_school_timetable_subject_fk FOREIGN KEY (subject_id) REFERENCES tbl_subjects (id) ON DELETE CASCADE,
  CONSTRAINT tbl_school_timetable_teacher_fk FOREIGN KEY (teacher_id) REFERENCES tbl_staff (id) ON DELETE CASCADE,
  CONSTRAINT tbl_school_timetable_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_school_timetable_term_class_idx
  ON tbl_school_timetable (term_id, class_id, day_name, start_time);

INSERT INTO tbl_grading_systems (name, type, description, is_default, is_active)
SELECT 'Default Marks System', 'marks', 'Standard marks grading for marks-based exams', 1, 1
WHERE NOT EXISTS (SELECT 1 FROM tbl_grading_systems);

INSERT INTO tbl_grading_scales (grading_system_id, min_score, max_score, grade, points, remark, sort_order, is_active)
SELECT gs.id, g.min, g.max, g.name, 0, g.remark, ROW_NUMBER() OVER (ORDER BY g.min DESC), 1
FROM tbl_grading_systems gs
JOIN tbl_grade_system g ON 1=1
WHERE gs.is_default = 1
  AND NOT EXISTS (
    SELECT 1 FROM tbl_grading_scales s WHERE s.grading_system_id = gs.id
  );

INSERT INTO tbl_grading_systems (name, type, description, is_default, is_active)
SELECT 'CBC Term System', 'cbc', 'CBC competency grading used for Junior School assessments', 0, 1
WHERE NOT EXISTS (SELECT 1 FROM tbl_grading_systems WHERE type = 'cbc');

INSERT INTO tbl_grading_scales (grading_system_id, min_score, max_score, grade, points, remark, sort_order, is_active)
SELECT gs.id, c.min_mark, c.max_mark, c.level, c.points, c.level, c.sort_order, c.active
FROM tbl_grading_systems gs
JOIN tbl_cbc_grading c ON 1=1
WHERE gs.type = 'cbc'
  AND NOT EXISTS (
    SELECT 1 FROM tbl_grading_scales s WHERE s.grading_system_id = gs.id
  );

INSERT INTO tbl_app_settings (setting_key, setting_value)
VALUES
  ('school_motto', ''),
  ('school_code', ''),
  ('school_email', ''),
  ('school_phone', ''),
  ('school_address', ''),
  ('school_website', ''),
  ('school_timezone', 'Africa/Nairobi'),
  ('current_academic_year', '2026'),
  ('current_term_id', ''),
  ('ranking_enabled', '1'),
  ('cbc_public_ranking_enabled', '0'),
  ('allow_mark_adjustments', '1'),
  ('require_review_before_finalizing', '1'),
  ('block_finalization_on_missing_marks', '1'),
  ('allow_partial_results', '0'),
  ('continuous_weight', '60'),
  ('summative_weight', '40'),
  ('autosave_interval_seconds', '10'),
  ('session_timeout_minutes', '60'),
  ('sms_enabled', '0'),
  ('email_enabled', '0'),
  ('send_results_automatically', '0'),
  ('mark_entry_deadline_days', '7'),
  ('default_school_days', 'Monday,Tuesday,Wednesday,Thursday,Friday')
ON CONFLICT (setting_key) DO NOTHING;

COMMIT;
