BEGIN;

CREATE TABLE IF NOT EXISTS tbl_certificates (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id varchar(64) NOT NULL,
  class_id integer NULL,
  certificate_type varchar(50) NOT NULL,
  title varchar(180) NOT NULL,
  serial_no varchar(80) NOT NULL,
  issue_date date NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'issued',
  notes text NULL,
  verification_code varchar(80) NOT NULL,
  cert_hash varchar(128) NOT NULL,
  issued_by integer NULL,
  downloads integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_certificates_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE,
  CONSTRAINT tbl_certificates_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE SET NULL,
  CONSTRAINT tbl_certificates_staff_fk FOREIGN KEY (issued_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_certificates_serial_uk ON tbl_certificates (serial_no);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_certificates_code_uk ON tbl_certificates (verification_code);
CREATE INDEX IF NOT EXISTS tbl_certificates_student_idx ON tbl_certificates (student_id, issue_date DESC);

COMMIT;
