BEGIN;

CREATE TABLE IF NOT EXISTS tbl_receipts (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payment_id integer NOT NULL,
  receipt_number varchar(80) NOT NULL,
  generated_by integer NULL,
  file_url varchar(255) NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_receipts_payment_fk FOREIGN KEY (payment_id) REFERENCES tbl_payments (id) ON DELETE CASCADE,
  CONSTRAINT tbl_receipts_staff_fk FOREIGN KEY (generated_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_receipts_number_uk ON tbl_receipts (receipt_number);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_receipts_payment_uk ON tbl_receipts (payment_id);

COMMIT;
