BEGIN;

INSERT INTO tbl_permissions (code, description) VALUES
('sms.wallet.manage', 'Manage SMS wallet and top-ups'),
('sms.send', 'Send SMS messages')
ON CONFLICT (code) DO NOTHING;

INSERT INTO tbl_roles (name, level, description, is_system) VALUES
('Headteacher', 0, 'Full school control', true),
('Deputy Headteacher', 1, 'Deputy school leadership and academic oversight', true),
('HOD', 2, 'Head of department with academic coordination rights', true),
('Exam Officer', 2, 'Exam operations, result publishing and communication', true)
ON CONFLICT (name) DO UPDATE SET level = EXCLUDED.level, description = EXCLUDED.description;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM tbl_roles r
JOIN tbl_permissions p ON p.code IN (
	'system.manage','audit.view','students.manage','staff.manage','attendance.manage','exams.manage','marks.enter',
	'results.approve','results.lock','results.unlock','report.generate','report.view','finance.manage','finance.view',
	'communication.manage','transport.manage','library.manage','inventory.manage','sms.wallet.manage','sms.send'
)
WHERE r.name = 'Headteacher'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM tbl_roles r
JOIN tbl_permissions p ON p.code IN (
	'audit.view','students.manage','staff.manage','attendance.manage','exams.manage','marks.enter','results.approve',
	'results.lock','results.unlock','report.generate','report.view','finance.view','communication.manage','transport.manage',
	'library.manage','inventory.manage','sms.send'
)
WHERE r.name = 'Deputy Headteacher'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM tbl_roles r
JOIN tbl_permissions p ON p.code IN (
	'attendance.manage','marks.enter','report.view','communication.manage','sms.send'
)
WHERE r.name = 'HOD'
ON CONFLICT DO NOTHING;

INSERT INTO tbl_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM tbl_roles r
JOIN tbl_permissions p ON p.code IN (
	'exams.manage','marks.enter','results.approve','results.lock','results.unlock','report.generate','report.view','communication.manage','sms.send'
)
WHERE r.name = 'Exam Officer'
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS tbl_sms_wallets (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wallet_name varchar(120) NOT NULL DEFAULT 'School SMS Wallet',
  phone_number varchar(30) NOT NULL DEFAULT '',
  balance_tokens integer NOT NULL DEFAULT 0,
  status integer NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_sms_token_transactions (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wallet_id integer NOT NULL,
  txn_type varchar(20) NOT NULL,
  tokens integer NOT NULL,
  reference_no varchar(120) NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_sms_token_transactions_wallet_fk FOREIGN KEY (wallet_id) REFERENCES tbl_sms_wallets (id) ON DELETE CASCADE,
  CONSTRAINT tbl_sms_token_transactions_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_sms_topup_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wallet_id integer NOT NULL,
  phone varchar(30) NOT NULL,
  tokens integer NOT NULL,
  amount numeric(12,2) NOT NULL DEFAULT 0,
  account_reference varchar(60) NOT NULL DEFAULT '',
  status varchar(20) NOT NULL DEFAULT 'pending',
  merchant_request_id varchar(80) NOT NULL DEFAULT '',
  checkout_request_id varchar(80) NOT NULL DEFAULT '',
  response_code varchar(20) NOT NULL DEFAULT '',
  response_desc varchar(255) NOT NULL DEFAULT '',
  customer_message varchar(255) NOT NULL DEFAULT '',
  result_code integer NULL,
  result_desc varchar(255) NOT NULL DEFAULT '',
  mpesa_receipt varchar(60) NOT NULL DEFAULT '',
  raw_callback text NOT NULL DEFAULT '',
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT tbl_sms_topup_requests_wallet_fk FOREIGN KEY (wallet_id) REFERENCES tbl_sms_wallets (id) ON DELETE CASCADE,
  CONSTRAINT tbl_sms_topup_requests_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS tbl_sms_topup_requests_checkout_idx ON tbl_sms_topup_requests (checkout_request_id);
CREATE INDEX IF NOT EXISTS tbl_sms_topup_requests_wallet_idx ON tbl_sms_topup_requests (wallet_id);

INSERT INTO tbl_sms_wallets (id, wallet_name, phone_number, balance_tokens, status)
SELECT 1, 'School SMS Wallet', '', 0, 1
WHERE NOT EXISTS (SELECT 1 FROM tbl_sms_wallets WHERE id = 1);

COMMIT;
