-- Migration 036: Enhanced Finance Module
-- Date: 2026-04-13
-- Features: Installment plans, fee reminders, aging analysis, revenue tracking

-- Installment Plans Table
CREATE TABLE IF NOT EXISTS tbl_fee_installments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id integer NOT NULL UNIQUE,
    number_of_installments integer NOT NULL DEFAULT 2 CHECK (number_of_installments > 0),
    installment_amount numeric(10,2) NOT NULL,
    first_due_date date,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    CONSTRAINT tbl_fee_installments_invoice_fk FOREIGN KEY (invoice_id) REFERENCES tbl_invoices (id) ON DELETE CASCADE,
    CONSTRAINT tbl_fee_installments_staff_fk FOREIGN KEY (created_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS tbl_fee_installments_invoice_idx ON tbl_fee_installments (invoice_id);

-- Installment Payment Schedule
CREATE TABLE IF NOT EXISTS tbl_installment_schedule (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installment_id integer NOT NULL,
    installment_number integer NOT NULL,
    due_date date NOT NULL,
    amount_due numeric(10,2) NOT NULL,
    amount_paid numeric(10,2) NOT NULL DEFAULT 0,
    paid_date timestamp,
    status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'overdue', 'cancelled')),
    CONSTRAINT tbl_installment_schedule_installment_fk FOREIGN KEY (installment_id) REFERENCES tbl_fee_installments (id) ON DELETE CASCADE,
    UNIQUE (installment_id, installment_number)
);
CREATE INDEX IF NOT EXISTS tbl_installment_schedule_installment_idx ON tbl_installment_schedule (installment_id);
CREATE INDEX IF NOT EXISTS tbl_installment_schedule_status_idx ON tbl_installment_schedule (status, due_date);

-- Fee Reminders Queue
CREATE TABLE IF NOT EXISTS tbl_fee_reminders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id integer NOT NULL,
    student_id integer NOT NULL,
    phone_number varchar(20),
    email_address varchar(100),
    reminder_type varchar(20) NOT NULL DEFAULT 'sms' CHECK (reminder_type IN ('sms', 'email', 'both')),
    days_before_due integer DEFAULT 7,
    amount_due numeric(10,2) NOT NULL,
    sent_at timestamp,
    status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    failure_reason text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tbl_fee_reminders_invoice_fk FOREIGN KEY (invoice_id) REFERENCES tbl_invoices (id) ON DELETE CASCADE,
    CONSTRAINT tbl_fee_reminders_student_fk FOREIGN KEY (student_id) REFERENCES tbl_students (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS tbl_fee_reminders_status_idx ON tbl_fee_reminders (status, sent_at);
CREATE INDEX IF NOT EXISTS tbl_fee_reminders_invoice_idx ON tbl_fee_reminders (invoice_id);

-- Revenue Recognition Journal
CREATE TABLE IF NOT EXISTS tbl_revenue_journal (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id integer NOT NULL,
    invoice_id integer NOT NULL,
    revenue_date date NOT NULL,
    amount numeric(10,2) NOT NULL,
    recognition_type varchar(20) NOT NULL DEFAULT 'cash' CHECK (recognition_type IN ('cash', 'accrual', 'deferred')),
    gl_account varchar(20),
    reference_number varchar(50),
    posted_at timestamp,
    posted_by integer,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tbl_revenue_journal_payment_fk FOREIGN KEY (payment_id) REFERENCES tbl_payments (id) ON DELETE CASCADE,
    CONSTRAINT tbl_revenue_journal_invoice_fk FOREIGN KEY (invoice_id) REFERENCES tbl_invoices (id) ON DELETE CASCADE,
    CONSTRAINT tbl_revenue_journal_staff_fk FOREIGN KEY (posted_by) REFERENCES tbl_staff (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS tbl_revenue_journal_revenue_date_idx ON tbl_revenue_journal (revenue_date);
CREATE INDEX IF NOT EXISTS tbl_revenue_journal_type_idx ON tbl_revenue_journal (recognition_type);

-- Financial Report Cache (for performance)
CREATE TABLE IF NOT EXISTS tbl_financial_reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type varchar(50) NOT NULL,
    class_id integer,
    term_id integer,
    report_date date NOT NULL,
    report_data jsonb,
    generated_by integer,
    generated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp,
    CONSTRAINT tbl_financial_reports_class_fk FOREIGN KEY (class_id) REFERENCES tbl_classes (id) ON DELETE SET NULL,
    CONSTRAINT tbl_financial_reports_term_fk FOREIGN KEY (term_id) REFERENCES tbl_terms (id) ON DELETE SET NULL,
    CONSTRAINT tbl_financial_reports_staff_fk FOREIGN KEY (generated_by) REFERENCES tbl_staff (id) ON DELETE SET NULL,
    UNIQUE (report_type, class_id, term_id, report_date)
);
CREATE INDEX IF NOT EXISTS tbl_financial_reports_type_idx ON tbl_financial_reports (report_type, report_date);

-- Payment Method Statistics
CREATE TABLE IF NOT EXISTS tbl_payment_method_stats (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date date NOT NULL,
    payment_method varchar(20) NOT NULL,
    transaction_count integer NOT NULL DEFAULT 0,
    total_amount numeric(15,2) NOT NULL DEFAULT 0,
    CONSTRAINT tbl_payment_method_stats_unique UNIQUE (stat_date, payment_method)
);
CREATE INDEX IF NOT EXISTS tbl_payment_method_stats_date_idx ON tbl_payment_method_stats (stat_date);
