BEGIN;

CREATE TABLE IF NOT EXISTS tbl_whatsapp_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  provider varchar(80) NOT NULL DEFAULT 'wireweb',
  api_url varchar(255) NOT NULL DEFAULT 'https://app.wireweb.co.in/api/v1/messages',
  api_key varchar(200) NOT NULL DEFAULT '',
  session_id varchar(120) NOT NULL DEFAULT '',
  status integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_whatsapp_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recipient varchar(50) NOT NULL,
  message text NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'queued',
  provider varchar(50) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO tbl_whatsapp_settings (provider, api_url, api_key, session_id, status)
SELECT 'wireweb', 'https://app.wireweb.co.in/api/v1/messages', '', '', 0
WHERE NOT EXISTS (SELECT 1 FROM tbl_whatsapp_settings);

COMMIT;
