#!/usr/bin/env python3
import re
from pathlib import Path


IDENTITY_TABLES = [
    "tbl_announcements",
    "tbl_classes",
    "tbl_exam_results",
    "tbl_grade_system",
    "tbl_school",
    "tbl_smtp",
    "tbl_staff",
    "tbl_subjects",
    "tbl_subject_combinations",
    "tbl_terms",
]


def convert(mysql_sql: str) -> str:
    sql = mysql_sql

    # Transaction
    sql = sql.replace("START TRANSACTION;", "BEGIN;")

    # Drop MySQL-only SET directives and versioned comments
    sql = re.sub(r"^SET [^;]+;\s*$\n?", "", sql, flags=re.M)
    sql = re.sub(r"^/\*![0-9]+ .*?\*/;\s*$\n?", "", sql, flags=re.M)

    # Remove backticks
    sql = sql.replace("`", "")

    # Types
    sql = re.sub(r"\blongtext\b", "text", sql, flags=re.I)
    sql = re.sub(r"\bdatetime\b", "timestamp", sql, flags=re.I)

    # Remove collation / comments on columns
    sql = re.sub(r" COLLATE [a-zA-Z0-9_]+", "", sql)
    sql = re.sub(r" COMMENT '([^']|\\')*'", "", sql)

    # Defaults: numeric values in quotes -> unquoted
    sql = re.sub(r"DEFAULT '([0-9]+)'", r"DEFAULT \1", sql)

    # AUTO_INCREMENT -> identity (most tables use integer id)
    sql = re.sub(
        r"\bint NOT NULL AUTO_INCREMENT\b",
        "integer GENERATED BY DEFAULT AS IDENTITY NOT NULL",
        sql,
        flags=re.I,
    )

    # int -> integer
    sql = re.sub(r"(?<![a-zA-Z0-9_])int(?![a-zA-Z0-9_])", "integer", sql, flags=re.I)

    # Drop table: add CASCADE so reruns work
    sql = re.sub(
        r"^DROP TABLE IF EXISTS ([^;]+);",
        r"DROP TABLE IF EXISTS \1 CASCADE;",
        sql,
        flags=re.M,
    )

    # Remove MySQL table options
    sql = re.sub(r"\)\s*ENGINE=.*?;\s*$", r");", sql, flags=re.M | re.S)

    # Remove MySQL KEY lines inside CREATE TABLE (we skip indexes for now)
    sql = re.sub(r"^\s*KEY [^(]+\([^)]+\),?\s*$\n?", "", sql, flags=re.M)

    # Fix trailing commas before closing parens after KEY removal
    sql = re.sub(r",\s*\n\)", "\n)", sql)

    # phpMyAdmin header comments about DB name are fine to keep.

    # Append sequence fixes for identity columns after data inserts
    seq_sql = "\n\n-- Set identity sequences after inserts\n"
    for t in IDENTITY_TABLES:
        seq_sql += (
            f"SELECT setval(pg_get_serial_sequence('{t}', 'id'), "
            f"COALESCE((SELECT MAX(id) FROM {t}), 1), true);\n"
        )

    # Insert before the final COMMIT if present, otherwise at end
    if "COMMIT;" in sql:
        sql = sql.replace("COMMIT;", seq_sql + "\nCOMMIT;")
    else:
        sql += seq_sql

    return sql


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    src = repo_root / "srms" / "database" / "srms_makumbusho.sql"
    dst = repo_root / "srms" / "database" / "srms_postgres.sql"

    mysql_sql = src.read_text(encoding="utf-8", errors="replace")
    pg_sql = convert(mysql_sql)
    dst.write_text(pg_sql, encoding="utf-8")
    print(f"Wrote {dst}")


if __name__ == "__main__":
    main()
