<?php
chdir('../');
session_start();
require_once('db/config.php');
require_once('const/check_session.php');

header('Content-Type: application/json');

if ($res != "1") {
	echo json_encode(['ok' => false, 'message' => 'Unauthorized']);
	exit;
}

$payload = json_decode(file_get_contents('php://input'), true);
if (!is_array($payload)) {
	$payload = $_POST;
}

$action = trim((string)($_GET['action'] ?? $payload['action'] ?? ''));

function app_role_from_level(int $level): string
{
	if ($level === 3) { return 'student'; }
	if ($level === 4) { return 'parent'; }
	if ($level === 2) { return 'teacher'; }
	if ($level === 0) { return 'admin'; }
	if ($level === 1) { return 'admin'; }
	if ($level === 5) { return 'accountant'; }
	return 'staff';
}

function app_ensure_edubot_memory_table(PDO $conn): void
{
	if (app_table_exists($conn, 'tbl_edubot_memory')) {
		return;
	}

	if (DBDriver === 'pgsql') {
		$conn->exec("CREATE TABLE IF NOT EXISTS tbl_edubot_memory (
			id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
			actor_type varchar(20) NOT NULL,
			actor_id varchar(50) NOT NULL,
			role varchar(20) NOT NULL,
			intent varchar(50) NOT NULL DEFAULT 'general',
			message text NOT NULL,
			response text NOT NULL,
			created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id)
		)");
		$conn->exec("CREATE INDEX IF NOT EXISTS tbl_edubot_memory_actor_idx ON tbl_edubot_memory (actor_type, actor_id, id DESC)");
		return;
	}

	$conn->exec("CREATE TABLE IF NOT EXISTS tbl_edubot_memory (
		id int NOT NULL AUTO_INCREMENT,
		actor_type varchar(20) NOT NULL,
		actor_id varchar(50) NOT NULL,
		role varchar(20) NOT NULL,
		intent varchar(50) NOT NULL DEFAULT 'general',
		message text NOT NULL,
		response text NOT NULL,
		created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (id),
		KEY tbl_edubot_memory_actor_idx (actor_type, actor_id, id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
}

function app_edubot_history_text(PDO $conn, string $actorType, string $actorId, int $limit = 8): string
{
	$history = app_ai_history($conn, $actorType, $actorId, $limit);
	if (empty($history)) {
		return '';
	}

	$lines = [];
	foreach ($history as $item) {
		$role = strtoupper((string)($item['role'] ?? 'user'));
		$text = trim((string)($item['text'] ?? ''));
		if ($text !== '') {
			$lines[] = $role . ': ' . $text;
		}
	}

	return implode("\n", $lines);
}

if ($action === 'history') {
	try {
		$conn = app_db();
		$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
		app_ensure_edubot_memory_table($conn);

		$actorType = 'staff';
		if ((int)$level === 3) { $actorType = 'student'; }
		if ((int)$level === 4) { $actorType = 'parent'; }
		$actorId = (string)$account_id;

		echo json_encode([
			'ok' => true,
			'user_key' => $actorType . ':' . $actorId,
			'role' => app_role_from_level((int)$level),
			'history' => app_ai_history($conn, $actorType, $actorId, 30),
		]);
	} catch (Throwable $e) {
		echo json_encode(['ok' => true, 'history' => []]);
	}
	exit;
}

$message = trim((string)($payload['message'] ?? ''));
$category = trim((string)($payload['category'] ?? 'feedback'));
if ($message === '') {
	echo json_encode(['ok' => false, 'message' => 'Message required']);
	exit;
}

function app_ai_suffix(string $response): string
{
	$response = trim($response);
	if ($response === '') {
		return 'School Assistant';
	}
	if (preg_match('/\s+School Assistant$/i', $response)) {
		return $response;
	}
	return $response . ' School Assistant';
}

function app_cbc_grade_from_points(float $points): string
{
	if ($points >= 3.5) {
		return 'EE';
	}
	if ($points >= 2.5) {
		return 'ME';
	}
	if ($points >= 1.5) {
		return 'AE';
	}
	return 'BE';
}

function app_edubot_store_memory(PDO $conn, string $actorType, string $actorId, string $role, string $intent, string $message, string $response): void
{
	if (!app_table_exists($conn, 'tbl_edubot_memory')) {
		return;
	}

	$stmt = $conn->prepare("INSERT INTO tbl_edubot_memory (actor_type, actor_id, role, intent, message, response) VALUES (?,?,?,?,?,?)");
	$stmt->execute([$actorType, $actorId, $role, $intent, $message, $response]);
}

function app_feedback_subject_from_message(string $message): string
{
	$message = trim(preg_replace('/\s+/', ' ', $message));
	if ($message === '') {
		return 'General feedback';
	}
	if (function_exists('mb_substr')) {
		return mb_substr($message, 0, 80);
	}
	return substr($message, 0, 80);
}

function app_store_ai_feedback(PDO $conn, string $actorType, string $actorId, string $category, string $subject, string $message, string $aiResponse, string $status = 'open', string $replyMessage = ''): void
{
	app_ensure_edubot_memory_table($conn);
	if (!app_table_exists($conn, 'tbl_ai_feedback')) {
		return;
	}

	$columns = ['actor_type', 'actor_id', 'category', 'message', 'ai_response'];
	$values = [$actorType, $actorId, $category, $message, $aiResponse];
	$placeholders = ['?', '?', '?', '?', '?'];

	if (app_column_exists($conn, 'tbl_ai_feedback', 'subject')) {
		$columns[] = 'subject';
		$values[] = $subject;
		$placeholders[] = '?';
	}
	if (app_column_exists($conn, 'tbl_ai_feedback', 'status')) {
		$columns[] = 'status';
		$values[] = $status;
		$placeholders[] = '?';
	}
	if (app_column_exists($conn, 'tbl_ai_feedback', 'reply_message')) {
		$columns[] = 'reply_message';
		$values[] = $replyMessage;
		$placeholders[] = '?';
	}
	if (app_column_exists($conn, 'tbl_ai_feedback', 'replied_by')) {
		$columns[] = 'replied_by';
		$values[] = null;
		$placeholders[] = '?';
	}

	$sql = "INSERT INTO tbl_ai_feedback (" . implode(',', $columns) . ") VALUES (" . implode(',', $placeholders) . ")";
	$stmt = $conn->prepare($sql);
	$stmt->execute($values);
}

try {
	$conn = app_db();
	$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	app_ensure_edubot_memory_table($conn);

	$actorType = 'staff';
	if ((int)$level === 3) { $actorType = 'student'; }
	if ((int)$level === 4) { $actorType = 'parent'; }
	$actorId = (string)$account_id;

	$role = app_role_from_level((int)$level);
	$intent = app_detect_intent($message);
	$historyText = app_edubot_history_text($conn, $actorType, $actorId, 8);

	if ($category !== 'ai') {
		$response = 'Thanks! We received your message.';
		app_store_ai_feedback($conn, $actorType, $actorId, $category, app_feedback_subject_from_message($message), $message, $response, 'open', '');
		app_edubot_store_memory($conn, $actorType, $actorId, $role, $intent, $message, $response);
		echo json_encode(['ok' => true, 'response' => $response]);
		exit;
	}

	if (app_is_restricted_question($message, $role)) {
		$response = 'You are not allowed to access that information in this portal.';
		app_ai_log($conn, $actorType, $actorId, $role, $message, $response, $intent);
		app_edubot_store_memory($conn, $actorType, $actorId, $role, $intent, $message, $response);
		echo json_encode(['ok' => true, 'response' => $response]);
		exit;
	}

	$scope = app_ai_scope($conn, $role, $actorId);
	$response = app_generate_ai_reply($message, $scope, $role, $intent);
	$openai = app_openai_reply($message, $scope, $role, $intent, $historyText);
	if ($openai !== '') {
		$response = $openai;
	}
	$response = app_ai_suffix($response);

	app_ai_log($conn, $actorType, $actorId, $role, $message, $response, $intent);
	app_edubot_store_memory($conn, $actorType, $actorId, $role, $intent, $message, $response);
	app_store_ai_feedback($conn, $actorType, $actorId, 'ai', $intent, $message, $response, 'answered', '');
	echo json_encode(['ok' => true, 'response' => $response]);
} catch (Throwable $e) {
	// Log exception for debugging and return generic error to client
	error_log('[ai_feedback] Failed to store AI message: ' . $e->getMessage() . "\n" . $e->getTraceAsString());
	echo json_encode(['ok' => false, 'message' => 'Failed to save message']);
}

function app_detect_intent(string $message): string
{
	$lower = strtolower($message);
	if (preg_match('/\b(hi|hello|hey|good morning|good afternoon|good evening)\b/', $lower)) {
		return 'greeting';
	}
	if (strpos($lower, 'top 5 students') !== false || strpos($lower, 'top students') !== false || strpos($lower, 'best students') !== false) {
		return 'top_students';
	}
	if (strpos($lower, 'weak students') !== false || strpos($lower, 'at risk') !== false || strpos($lower, 'failing') !== false) {
		return 'weak_students';
	}
	if (strpos($lower, 'class performance') !== false || strpos($lower, 'class summary') !== false) {
		return 'class_performance';
	}
	if (strpos($lower, 'attendance summary') !== false || strpos($lower, 'attendance report') !== false) {
		return 'attendance_summary';
	}
	if (strpos($lower, 'fee') !== false || strpos($lower, 'payment') !== false || strpos($lower, 'balance') !== false) {
		return 'fees';
	}
	if (strpos($lower, 'attendance') !== false || strpos($lower, 'absent') !== false) {
		return 'attendance';
	}
	if (strpos($lower, 'result') !== false || strpos($lower, 'mark') !== false || strpos($lower, 'score') !== false || strpos($lower, 'performance') !== false) {
		return 'performance';
	}
	if (strpos($lower, 'assignment') !== false || strpos($lower, 'quiz') !== false) {
		return 'assignments';
	}
	if (strpos($lower, 'report card') !== false || strpos($lower, 'report') !== false || strpos($lower, 'publish') !== false) {
		return 'report';
	}
	if (strpos($lower, 'timetable') !== false || strpos($lower, 'schedule') !== false || strpos($lower, 'drag') !== false) {
		return 'timetable';
	}
	if (strpos($lower, 'class') !== false && (strpos($lower, 'best') !== false || strpos($lower, 'top') !== false)) {
		return 'analytics';
	}
	if (strpos($lower, 'live class') !== false || strpos($lower, 'meeting') !== false) {
		return 'live';
	}
	if (strpos($lower, 'cbc') !== false || strpos($lower, 'point') !== false || strpos($lower, 'grade') !== false) {
		return 'cbc';
	}
	return 'general';
}

function app_is_restricted_question(string $message, string $role): bool
{
	$lower = strtolower($message);
	$restrictedKeywords = [
		'all students', 'other students', 'top student', 'best student', 'ranking', 'rank', 'leaderboard'
	];
	foreach ($restrictedKeywords as $keyword) {
		if (strpos($lower, $keyword) !== false) {
			return in_array($role, ['student', 'parent'], true);
		}
	}
	return false;
}

function app_ai_scope(PDO $conn, string $role, string $actorId): array
{
	$scope = [
		'role' => $role,
		'profile' => [],
		'students' => [],
		'teacher' => [],
		'school' => [],
	];

	if ($role === 'student') {
		$scope['profile'] = app_student_profile($conn, $actorId);
		$scope['students'][] = app_student_summary($conn, $actorId, $scope['profile']['class_id'] ?? null);
		return $scope;
	}

	if ($role === 'parent') {
		$children = app_parent_children($conn, (int)$actorId);
		foreach ($children as $studentId) {
			$scope['students'][] = app_student_summary($conn, $studentId, null);
		}
		return $scope;
	}

	if ($role === 'teacher') {
		$scope['teacher'] = app_teacher_scope($conn, (int)$actorId);
		return $scope;
	}

	if ($role === 'accountant') {
		$scope['school'] = app_accountant_scope($conn);
		return $scope;
	}

	$scope['school'] = app_school_scope($conn);
	return $scope;
}

function app_student_profile(PDO $conn, string $studentId): array
{
	if (!app_table_exists($conn, 'tbl_students')) {
		return [];
	}
	$stmt = $conn->prepare("SELECT st.id, st.fname, st.lname, st.class, c.name as class_name FROM tbl_students st LEFT JOIN tbl_classes c ON c.id = st.class WHERE st.id = ? LIMIT 1");
	$stmt->execute([$studentId]);
	$row = $stmt->fetch(PDO::FETCH_ASSOC);
	if (!$row) {
		return [];
	}
	return [
		'id' => (string)$row['id'],
		'name' => trim($row['fname'].' '.$row['lname']),
		'class_id' => (int)$row['class'],
		'class_name' => (string)($row['class_name'] ?? ''),
	];
}

function app_parent_children(PDO $conn, int $parentId): array
{
	if ($parentId < 1 || !app_table_exists($conn, 'tbl_parent_students')) {
		return [];
	}
	$stmt = $conn->prepare("SELECT student_id FROM tbl_parent_students WHERE parent_id = ?");
	$stmt->execute([$parentId]);
	$students = $stmt->fetchAll(PDO::FETCH_COLUMN);
	return array_slice(array_map('strval', $students), 0, 3);
}

function app_student_summary(PDO $conn, string $studentId, ?int $classId): array
{
	$profile = app_student_profile($conn, $studentId);
	$classId = $classId ?? ($profile['class_id'] ?? null);

	$summary = [
		'id' => $studentId,
		'name' => $profile['name'] ?? '',
		'class_name' => $profile['class_name'] ?? '',
		'attendance_rate' => null,
		'avg_score' => null,
		'top_subjects' => [],
		'cbc_levels' => [],
		'fees' => null,
		'assignments' => null,
		'live_classes' => [],
	];

	if (app_table_exists($conn, 'tbl_attendance_records')) {
		$stmt = $conn->prepare("SELECT SUM(CASE WHEN status = 'present' THEN 1 ELSE 0 END) AS present_count, COUNT(*) AS total_count FROM tbl_attendance_records WHERE student_id = ?");
		$stmt->execute([$studentId]);
		$row = $stmt->fetch(PDO::FETCH_ASSOC) ?: [];
		$total = (int)($row['total_count'] ?? 0);
		if ($total > 0) {
			$summary['attendance_rate'] = round(((int)$row['present_count'] / $total) * 100, 1);
		}
	}

	if (app_table_exists($conn, 'tbl_exam_results')) {
		$stmt = $conn->prepare("SELECT AVG(score) AS avg_score FROM tbl_exam_results WHERE student = ?");
		$stmt->execute([$studentId]);
		$avg = $stmt->fetchColumn();
		if ($avg !== false) {
			$summary['avg_score'] = round((float)$avg, 2);
		}

		if (app_table_exists($conn, 'tbl_subject_combinations') && app_table_exists($conn, 'tbl_subjects')) {
			$stmt = $conn->prepare("SELECT s.name, AVG(er.score) AS avg_score
				FROM tbl_exam_results er
				JOIN tbl_subject_combinations sc ON sc.id = er.subject_combination
				JOIN tbl_subjects s ON s.id = sc.subject
				WHERE er.student = ?
				GROUP BY s.name
				ORDER BY avg_score DESC
				LIMIT 3");
			$stmt->execute([$studentId]);
			$summary['top_subjects'] = $stmt->fetchAll(PDO::FETCH_ASSOC);
		}
	}

	if (app_table_exists($conn, 'tbl_cbc_assessments')) {
		$stmt = $conn->prepare("SELECT learning_area, level, COUNT(*) AS entries
			FROM tbl_cbc_assessments
			WHERE student_id = ?
			GROUP BY learning_area, level
			ORDER BY learning_area");
		$stmt->execute([$studentId]);
		$summary['cbc_levels'] = $stmt->fetchAll(PDO::FETCH_ASSOC);
	}

	if ($classId && app_table_exists($conn, 'tbl_assignments') && app_table_exists($conn, 'tbl_courses')) {
		$stmt = $conn->prepare("SELECT COUNT(*) FROM tbl_assignments a JOIN tbl_courses c ON c.id = a.course_id WHERE c.class_id = ?");
		$stmt->execute([$classId]);
		$totalAssignments = (int)$stmt->fetchColumn();

		if (app_table_exists($conn, 'tbl_assignment_submissions')) {
			$stmt = $conn->prepare("SELECT COUNT(*) FROM tbl_assignment_submissions WHERE student_id = ?");
			$stmt->execute([$studentId]);
			$submitted = (int)$stmt->fetchColumn();
			$summary['assignments'] = [
				'total' => $totalAssignments,
				'submitted' => $submitted,
			];
		}
	}

	if (app_table_exists($conn, 'tbl_invoices') && app_table_exists($conn, 'tbl_invoice_lines') && app_table_exists($conn, 'tbl_payments')) {
		$stmt = $conn->prepare("SELECT COALESCE(SUM(l.amount), 0) FROM tbl_invoice_lines l JOIN tbl_invoices i ON i.id = l.invoice_id WHERE i.student_id = ?");
		$stmt->execute([$studentId]);
		$total = (float)$stmt->fetchColumn();

		$stmt = $conn->prepare("SELECT COALESCE(SUM(p.amount), 0) FROM tbl_payments p JOIN tbl_invoices i ON i.id = p.invoice_id WHERE i.student_id = ?");
		$stmt->execute([$studentId]);
		$paid = (float)$stmt->fetchColumn();
		$summary['fees'] = [
			'total' => round($total, 2),
			'paid' => round($paid, 2),
			'balance' => round($total - $paid, 2),
		];
	}

	if ($classId && app_table_exists($conn, 'tbl_live_classes') && app_table_exists($conn, 'tbl_courses')) {
		$stmt = $conn->prepare("SELECT lc.title, lc.start_time, lc.platform
			FROM tbl_live_classes lc
			JOIN tbl_courses c ON c.id = lc.course_id
			WHERE c.class_id = ? AND lc.start_time >= NOW()
			ORDER BY lc.start_time
			LIMIT 2");
		$stmt->execute([$classId]);
		$summary['live_classes'] = $stmt->fetchAll(PDO::FETCH_ASSOC);
	}

	return $summary;
}

function app_teacher_scope(PDO $conn, int $teacherId): array
{
	$scope = [
		'classes' => [],
		'subjects' => [],
		'pending_marks' => 0,
	];

	if (!app_table_exists($conn, 'tbl_subject_combinations')) {
		return $scope;
	}

	$stmt = $conn->prepare("SELECT sc.id, sc.class, sc.subject, s.name AS subject_name
		FROM tbl_subject_combinations sc
		JOIN tbl_subjects s ON s.id = sc.subject
		WHERE sc.teacher = ?");
	$stmt->execute([$teacherId]);
	$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

	$classIds = [];
	foreach ($rows as $row) {
		$classes = @unserialize($row['class']);
		if (!is_array($classes)) {
			$classes = [];
		}
		foreach ($classes as $classId) {
			$classIds[] = (int)$classId;
		}
		$scope['subjects'][] = [
			'id' => (int)$row['subject'],
			'name' => (string)$row['subject_name'],
			'subject_combination_id' => (int)$row['id'],
		];
	}
	$classIds = array_values(array_unique($classIds));

	if (!empty($classIds) && app_table_exists($conn, 'tbl_classes')) {
		$placeholders = implode(',', array_fill(0, count($classIds), '?'));
		$stmt = $conn->prepare("SELECT id, name FROM tbl_classes WHERE id IN ($placeholders)");
		$stmt->execute($classIds);
		$scope['classes'] = $stmt->fetchAll(PDO::FETCH_ASSOC);
	}

	if (app_table_exists($conn, 'tbl_exam_mark_submissions')) {
		$stmt = $conn->prepare("SELECT COUNT(*) FROM tbl_exam_mark_submissions WHERE teacher_id = ? AND status = 'draft'");
		$stmt->execute([$teacherId]);
		$scope['pending_marks'] = (int)$stmt->fetchColumn();
	}

	return $scope;
}

function app_school_scope(PDO $conn): array
{
	$stats = [
		'students' => 0,
		'staff' => 0,
		'attendance_rate' => null,
		'avg_score' => null,
		'report_cards' => 0,
		'published_terms' => 0,
		'timetable_slots' => 0,
	];

	if (app_table_exists($conn, 'tbl_students')) {
		$stmt = $conn->query("SELECT COUNT(*) FROM tbl_students");
		$stats['students'] = (int)$stmt->fetchColumn();
	}
	if (app_table_exists($conn, 'tbl_staff')) {
		$stmt = $conn->query("SELECT COUNT(*) FROM tbl_staff");
		$stats['staff'] = (int)$stmt->fetchColumn();
	}
	if (app_table_exists($conn, 'tbl_attendance_records')) {
		$stmt = $conn->query("SELECT SUM(CASE WHEN status = 'present' THEN 1 ELSE 0 END) AS present_count, COUNT(*) AS total_count FROM tbl_attendance_records");
		$row = $stmt->fetch(PDO::FETCH_ASSOC) ?: [];
		$total = (int)($row['total_count'] ?? 0);
		if ($total > 0) {
			$stats['attendance_rate'] = round(((int)$row['present_count'] / $total) * 100, 1);
		}
	}
	if (app_table_exists($conn, 'tbl_exam_results')) {
		$stmt = $conn->query("SELECT AVG(score) FROM tbl_exam_results");
		$avg = $stmt->fetchColumn();
		if ($avg !== false) {
			$stats['avg_score'] = round((float)$avg, 2);
		}
	}
	if (app_table_exists($conn, 'tbl_report_cards')) {
		$stmt = $conn->query("SELECT COUNT(*) FROM tbl_report_cards");
		$stats['report_cards'] = (int)$stmt->fetchColumn();
	}
	if (app_table_exists($conn, 'tbl_report_publication')) {
		$publicationStatusColumn = app_column_exists($conn, 'tbl_report_publication', 'status') ? 'status' : (app_column_exists($conn, 'tbl_report_publication', 'state') ? 'state' : '');
		if ($publicationStatusColumn !== '') {
			$stmt = $conn->query("SELECT COUNT(*) FROM tbl_report_publication WHERE {$publicationStatusColumn} = 'published'");
		} else {
			$stmt = $conn->query("SELECT COUNT(*) FROM tbl_report_publication");
		}
		$stats['published_terms'] = (int)$stmt->fetchColumn();
	}
	if (app_table_exists($conn, 'tbl_school_timetable')) {
		$stmt = $conn->query("SELECT COUNT(*) FROM tbl_school_timetable");
		$stats['timetable_slots'] = (int)$stmt->fetchColumn();
	}
	return $stats;
}

function app_accountant_scope(PDO $conn): array
{
	$stats = [
		'invoices' => 0,
		'collections' => 0,
		'outstanding' => 0,
	];

	if (app_table_exists($conn, 'tbl_invoices')) {
		$stmt = $conn->query("SELECT COUNT(*) FROM tbl_invoices");
		$stats['invoices'] = (int)$stmt->fetchColumn();
	}

	if (app_table_exists($conn, 'tbl_payments')) {
		$stmt = $conn->query("SELECT COALESCE(SUM(amount), 0) FROM tbl_payments");
		$stats['collections'] = round((float)$stmt->fetchColumn(), 2);
	}

	if (app_table_exists($conn, 'tbl_invoice_lines') && app_table_exists($conn, 'tbl_invoices')) {
		$stmt = $conn->query("SELECT COALESCE(SUM(l.amount), 0) FROM tbl_invoice_lines l JOIN tbl_invoices i ON i.id = l.invoice_id");
		$total = (float)$stmt->fetchColumn();
		$stats['outstanding'] = round($total - $stats['collections'], 2);
	}

	return $stats;
}

function app_generate_ai_reply(string $message, array $scope, string $role, string $intent): string
{
	$lower = strtolower($message);

	if ($intent === 'greeting') {
		$greetings = [
			'Hello, I\'m Edu Bot. How can I help you today?',
			'Hi there. I can help with reports, attendance, fees, and school analytics.',
			'Good day. Ask me about students, results, CBC points, or school reports.'
		];
		return $greetings[array_rand($greetings)];
	}

	if ($intent === 'fees') {
		$student = $scope['students'][0] ?? null;
		$fees = $student['fees'] ?? null;
		if ($fees) {
			return 'Fees summary: Total Ksh '.number_format($fees['total'], 2).', Paid Ksh '.number_format($fees['paid'], 2).', Balance Ksh '.number_format($fees['balance'], 2).'.';
		}
		if ($role === 'accountant' && !empty($scope['school'])) {
			return 'Collections: Ksh '.number_format((float)($scope['school']['collections'] ?? 0), 2).', Outstanding: Ksh '.number_format((float)($scope['school']['outstanding'] ?? 0), 2).'.';
		}
		return 'No fee records found yet for this account.';
	}

	if ($intent === 'attendance') {
		$student = $scope['students'][0] ?? null;
		$rate = $student['attendance_rate'] ?? null;
		if ($rate !== null) {
			return 'Attendance rate is '.$rate.'%.';
		}
		if (!empty($scope['school']['attendance_rate'])) {
			return 'School attendance rate is '.$scope['school']['attendance_rate'].'%.';
		}
		return 'Attendance data is not available yet.';
	}

	if ($intent === 'performance') {
		$student = $scope['students'][0] ?? null;
		if ($student) {
			$parts = [];
			if ($student['avg_score'] !== null) {
				$parts[] = 'Average score: '.$student['avg_score'];
			}
			if (!empty($student['top_subjects'])) {
				$tops = [];
				foreach ($student['top_subjects'] as $row) {
					$tops[] = $row['name'].' ('.round((float)$row['avg_score'], 1).')';
				}
				$parts[] = 'Top subjects: '.implode(', ', $tops);
			}
			if (!empty($parts)) {
				return implode('. ', $parts).'.';
			}
		}
		if (!empty($scope['school']['avg_score'])) {
			return 'School average score: '.$scope['school']['avg_score'].'.';
		}
		return 'No exam performance data yet.';
	}

	if ($intent === 'assignments') {
		$student = $scope['students'][0] ?? null;
		$assign = $student['assignments'] ?? null;
		if ($assign) {
			return 'Assignments: '.$assign['submitted'].' submitted out of '.$assign['total'].'.';
		}
		return 'No assignment data available yet.';
	}

	if ($intent === 'report') {
		$student = $scope['students'][0] ?? null;
		if ($student && $student['avg_score'] !== null) {
			$response = 'Report automation summary: current average score is '.$student['avg_score'].'.';
			if (!empty($student['top_subjects'])) {
				$tops = [];
				foreach ($student['top_subjects'] as $row) {
					$tops[] = $row['name'].' ('.round((float)$row['avg_score'], 1).')';
				}
				$response .= ' Strongest areas: '.implode(', ', $tops).'.';
			}
			$response .= ' Use Report Card to view AI summary and teacher/headteacher remarks.';
			return $response;
		}
		if (!empty($scope['school'])) {
			return 'Report automation status: '.(int)($scope['school']['report_cards'] ?? 0).' report cards generated, '.(int)($scope['school']['published_terms'] ?? 0).' published term releases. Admin can regenerate from Report > Generate Report Cards.';
		}
		return 'Report automation is available after marks are saved and results are locked.';
	}

	if ($intent === 'timetable') {
		if ($role === 'admin' || $role === 'teacher') {
			$slots = (int)($scope['school']['timetable_slots'] ?? 0);
			return 'Timetable automation is active. Current stored lesson slots: '.$slots.'. Use School Timetable to auto-generate conflict-free slots, then drag and drop lessons to swap safely.';
		}
		return 'Timetable updates are managed by school administrators. Ask for the latest class schedule from your portal timetable page.';
	}

	if ($intent === 'live') {
		$student = $scope['students'][0] ?? null;
		if (!empty($student['live_classes'])) {
			$next = $student['live_classes'][0];
			return 'Next live class: '.$next['title'].' on '.date('Y-m-d H:i', strtotime($next['start_time'])).' via '.$next['platform'].'.';
		}
		return 'No upcoming live classes found.';
	}

	if ($intent === 'analytics') {
		if ($role === 'teacher') {
			$pending = $scope['teacher']['pending_marks'] ?? 0;
			return 'You have '.$pending.' pending marks submissions. You can review from Marks Entry.';
		}
		if ($role === 'accountant') {
			$stats = $scope['school'] ?? [];
			return 'Finance snapshot: '.$stats['invoices'].' invoices, collections Ksh '.number_format((float)($stats['collections'] ?? 0), 2).', outstanding Ksh '.number_format((float)($stats['outstanding'] ?? 0), 2).'.';
		}
		if (!empty($scope['school'])) {
			return 'School snapshot: '.$scope['school']['students'].' students, '.$scope['school']['staff'].' staff.';
		}
	}

	if ($intent === 'top_students') {
		if (!app_table_exists(app_db(), 'tbl_report_cards')) {
			return 'Top student analytics is available after report cards are generated.';
		}
		try {
			$conn = app_db();
			$rows = [];
			if (app_table_exists($conn, 'tbl_report_cards') && app_table_exists($conn, 'tbl_students')) {
				$stmt = $conn->query("SELECT CONCAT(COALESCE(st.fname, ''), ' ', COALESCE(st.lname, '')) AS name, rc.mean, rc.grade
					FROM tbl_report_cards rc
					LEFT JOIN tbl_students st ON st.id = rc.student_id
					ORDER BY rc.mean DESC, rc.id DESC
					LIMIT 5");
				$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
			}
			if (empty($rows)) {
				return 'No top student data is available yet.';
			}
			$lines = [];
			foreach ($rows as $row) {
				$name = trim((string)($row['name'] ?? 'Student'));
				$points = round((float)($row['mean'] ?? 0), 2);
				$grade = trim((string)($row['grade'] ?? app_cbc_grade_from_points($points)));
				$lines[] = $name . ' - ' . $points . ' points (' . $grade . ')';
			}
			return "Top performing learners:\n" . implode("\n", $lines);
		} catch (Throwable $e) {
			return 'I could not load top student analytics right now.';
		}
	}

	if ($intent === 'weak_students') {
		try {
			$conn = app_db();
			if (!app_table_exists($conn, 'tbl_report_cards')) {
				return 'Weak student analytics is available after report cards are generated.';
			}
			$stmt = $conn->query("SELECT CONCAT(COALESCE(st.fname, ''), ' ', COALESCE(st.lname, '')) AS name, rc.mean, rc.grade
				FROM tbl_report_cards rc
				LEFT JOIN tbl_students st ON st.id = rc.student_id
				ORDER BY rc.mean ASC, rc.id ASC
				LIMIT 5");
			$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
			if (empty($rows)) {
				return 'No weak student data is available yet.';
			}
			$lines = [];
			foreach ($rows as $row) {
				$name = trim((string)($row['name'] ?? 'Student'));
				$points = round((float)($row['mean'] ?? 0), 2);
				$grade = trim((string)($row['grade'] ?? app_cbc_grade_from_points($points)));
				$lines[] = $name . ' - ' . $points . ' points (' . $grade . ')';
			}
			return "Students who may need support:\n" . implode("\n", $lines);
		} catch (Throwable $e) {
			return 'I could not load weak student analytics right now.';
		}
	}

	if ($intent === 'class_performance') {
		try {
			$conn = app_db();
			if (!app_table_exists($conn, 'tbl_report_cards') || !app_table_exists($conn, 'tbl_classes')) {
				return 'Class performance analytics is available after report cards are generated.';
			}
			$stmt = $conn->query("SELECT COALESCE(c.name, 'Unknown Class') AS class_name, ROUND(AVG(rc.mean), 2) AS avg_points
				FROM tbl_report_cards rc
				LEFT JOIN tbl_classes c ON c.id = rc.class_id
				GROUP BY c.name
				ORDER BY avg_points DESC");
			$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
			if (empty($rows)) {
				return 'No class performance data is available yet.';
			}
			$lines = [];
			foreach ($rows as $row) {
				$lines[] = trim((string)$row['class_name']) . ' - ' . number_format((float)($row['avg_points'] ?? 0), 2) . ' points';
			}
			return "Class performance snapshot:\n" . implode("\n", $lines);
		} catch (Throwable $e) {
			return 'I could not load class performance right now.';
		}
	}

	if ($intent === 'attendance_summary') {
		try {
			$conn = app_db();
			if (!app_table_exists($conn, 'tbl_attendance_records') || !app_table_exists($conn, 'tbl_students')) {
				return 'Attendance analytics is available after attendance has been recorded.';
			}
			$stmt = $conn->query("SELECT CONCAT(COALESCE(st.fname, ''), ' ', COALESCE(st.lname, '')) AS name,
				SUM(CASE WHEN ar.status = 'present' THEN 1 ELSE 0 END) AS present_days,
				COUNT(*) AS total_days
				FROM tbl_attendance_records ar
				LEFT JOIN tbl_students st ON st.id = ar.student_id
				GROUP BY ar.student_id
				ORDER BY present_days DESC, total_days DESC
				LIMIT 5");
			$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
			if (empty($rows)) {
				return 'No attendance records were found yet.';
			}
			$lines = [];
			foreach ($rows as $row) {
				$name = trim((string)($row['name'] ?? 'Student'));
				$present = (int)($row['present_days'] ?? 0);
				$total = (int)($row['total_days'] ?? 0);
				$lines[] = $name . ' - ' . $present . '/' . $total . ' days present';
			}
			return "Attendance snapshot:\n" . implode("\n", $lines);
		} catch (Throwable $e) {
			return 'I could not load attendance analytics right now.';
		}
	}

	if ($intent === 'cbc') {
		return 'CBC reporting uses points and grades together. Example: 4 = EE, 3 = ME, 2 = AE, 1 = BE.';
	}

	if ($intent === 'learning') {
		return 'Tell me the topic you want explained and I will guide you step-by-step.';
	}

	if (strpos($lower, 'assignment') !== false) {
		return 'Assignments are under E-Learning. Teachers create them; students submit in their portal.';
	}
	if (strpos($lower, 'results') !== false || strpos($lower, 'marks') !== false) {
		return 'Marks entry is under Exam Marks Entry (teachers) and Marks Review (admin). Results unlock only by admin.';
	}
	if (strpos($lower, 'report') !== false) {
		return 'Report cards use marks, attendance, fees status, ranking, and AI-generated comments. Admin can generate and publish them from the Report module.';
	}
	if (strpos($lower, 'timetable') !== false || strpos($lower, 'schedule') !== false) {
		return 'School timetable supports smart auto-generation and drag-and-drop slot swaps with conflict checks for class, teacher, and room.';
	}
	if (strpos($lower, 'attendance') !== false) {
		return 'Attendance is available under Attendance and Staff Attendance. Reports are on the dashboard.';
	}
	return 'Thanks for the message. Ask about performance, attendance, fees, or assignments to get a data-based answer.';
}

function app_openai_reply(string $message, array $scope, string $role, string $intent, string $historyText = ''): string
{
	$mode = strtolower(trim((string)getenv('AI_MODE')));
	if ($mode !== 'external') {
		return '';
	}
	$apiKey = trim((string)getenv('OPENAI_API_KEY'));
	if ($apiKey === '') {
		return '';
	}
	$model = trim((string)getenv('OPENAI_MODEL'));
	if ($model === '') {
		$model = 'gpt-4o-mini';
	}

	$systemPrompt = "You are the school's AI assistant. Follow role-based access. Role: ".$role.". ".
		"Never reveal data outside the allowed scope. Do not invent names or statistics. ".
		"Use CBC levels (EE/ME/AE/BE) and points (4, 3, 2, 1) when relevant. If data is missing, say so.";

	$context = json_encode($scope, JSON_UNESCAPED_SLASHES);
	$userPrompt = "User question: ".$message."\nIntent: ".$intent."\nAllowed data (JSON): ".$context;
	if ($historyText !== '') {
		$userPrompt .= "\nConversation history:\n" . $historyText;
	}

	$payload = json_encode([
		'model' => $model,
		'input' => [
			['role' => 'system', 'content' => $systemPrompt],
			['role' => 'user', 'content' => $userPrompt],
		],
		'temperature' => 0.2,
		'max_output_tokens' => 300,
	]);

	$ch = curl_init('https://api.openai.com/v1/responses');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_POST, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, [
		'Authorization: Bearer '.$apiKey,
		'Content-Type: application/json',
	]);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
	curl_setopt($ch, CURLOPT_TIMEOUT, 20);

	$result = curl_exec($ch);
	if ($result === false) {
		curl_close($ch);
		return '';
	}
	$httpCode = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
	curl_close($ch);
	if ($httpCode < 200 || $httpCode >= 300) {
		return '';
	}

	$data = json_decode($result, true);
	if (!is_array($data)) {
		return '';
	}

	if (isset($data['output_text']) && is_string($data['output_text'])) {
		return trim($data['output_text']);
	}

	if (isset($data['output']) && is_array($data['output'])) {
		foreach ($data['output'] as $item) {
			if (!empty($item['content']) && is_array($item['content'])) {
				foreach ($item['content'] as $content) {
					if (($content['type'] ?? '') === 'output_text' && isset($content['text'])) {
						return trim((string)$content['text']);
					}
				}
			}
		}
	}

	return '';
}

function app_ai_log(PDO $conn, string $actorType, string $actorId, string $role, string $question, string $response, string $intent): void
{
	try {
		if (app_table_exists($conn, 'tbl_ai_logs')) {
			$stmt = $conn->prepare("INSERT INTO tbl_ai_logs (actor_type, actor_id, role, question, response) VALUES (?,?,?,?,?)");
			$stmt->execute([$actorType, $actorId, $role, $question, $response]);
		}
		if (app_table_exists($conn, 'tbl_ai_queries')) {
			$stmt = $conn->prepare("INSERT INTO tbl_ai_queries (actor_type, actor_id, role, question, intent) VALUES (?,?,?,?,?)");
			$stmt->execute([$actorType, $actorId, $role, $question, $intent]);
		}
	} catch (Throwable $e) {
		// best-effort only
	}
}

function app_ai_history(PDO $conn, string $actorType, string $actorId, int $limit = 30): array
{
	if ($limit < 1) {
		$limit = 30;
	}
	$limit = min($limit, 100);

	$history = [];
	if (app_table_exists($conn, 'tbl_edubot_memory')) {
		$stmt = $conn->prepare("SELECT role, message, response, created_at
			FROM tbl_edubot_memory
			WHERE actor_type = ? AND actor_id = ?
			ORDER BY id DESC
			LIMIT " . (int)$limit);
		$stmt->execute([$actorType, $actorId]);
		$rows = array_reverse($stmt->fetchAll(PDO::FETCH_ASSOC));
		foreach ($rows as $row) {
			$q = trim((string)($row['message'] ?? ''));
			$r = trim((string)($row['response'] ?? ''));
			if ($q !== '') {
				$history[] = ['role' => 'user', 'text' => $q, 'created_at' => (string)($row['created_at'] ?? '')];
			}
			if ($r !== '') {
				$history[] = ['role' => 'edu', 'text' => $r, 'created_at' => (string)($row['created_at'] ?? '')];
			}
		}
		return array_slice($history, -60);
	}

	if (!app_table_exists($conn, 'tbl_ai_logs')) {
		return [];
	}

	$stmt = $conn->prepare("SELECT question, response, created_at
		FROM tbl_ai_logs
		WHERE actor_type = ? AND actor_id = ?
		ORDER BY id DESC
		LIMIT " . (int)$limit);
	$stmt->execute([$actorType, $actorId]);
	$rows = array_reverse($stmt->fetchAll(PDO::FETCH_ASSOC));

	foreach ($rows as $row) {
		$q = trim((string)($row['question'] ?? ''));
		$r = trim((string)($row['response'] ?? ''));
		if ($q !== '') {
			$history[] = ['role' => 'user', 'text' => $q, 'created_at' => (string)($row['created_at'] ?? '')];
		}
		if ($r !== '') {
			$history[] = ['role' => 'edu', 'text' => $r, 'created_at' => (string)($row['created_at'] ?? '')];
		}
	}

	return array_slice($history, -60);
}
