-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Sep 27, 2024 at 07:30 AM
-- Server version: 8.2.0
-- PHP Version: 8.2.13

BEGIN;
--
-- Database: srms_makumbusho
--

-- --------------------------------------------------------

--
-- Table structure for table tbl_announcements
--

DROP TABLE IF EXISTS tbl_announcements CASCADE;
CREATE TABLE IF NOT EXISTS tbl_announcements (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title varchar(90) NOT NULL,
  announcement text NOT NULL,
  create_date timestamp NOT NULL,
  level integer NOT NULL,
  PRIMARY KEY (id)
);
-- --------------------------------------------------------

--
-- Table structure for table tbl_classes
--

DROP TABLE IF EXISTS tbl_classes CASCADE;
CREATE TABLE IF NOT EXISTS tbl_classes (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(90) NOT NULL,
  registration_date timestamp NOT NULL,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_classes
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_division_system
--

DROP TABLE IF EXISTS tbl_division_system CASCADE;
CREATE TABLE IF NOT EXISTS tbl_division_system (
  division varchar(50) NOT NULL,
  min integer NOT NULL,
  max integer NOT NULL,
  min_point integer NOT NULL,
  max_point integer NOT NULL,
  points integer NOT NULL,
  PRIMARY KEY (division)
);
--
-- Dumping data for table tbl_division_system
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_exam_results
--

DROP TABLE IF EXISTS tbl_exam_results CASCADE;
CREATE TABLE IF NOT EXISTS tbl_exam_results (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student varchar(20) NOT NULL,
  class integer NOT NULL,
  subject_combination integer NOT NULL,
  term integer NOT NULL,
  score double precision NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_exam_results
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_grade_system
--

DROP TABLE IF EXISTS tbl_grade_system CASCADE;
CREATE TABLE IF NOT EXISTS tbl_grade_system (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(20) NOT NULL,
  min double precision NOT NULL,
  max double precision NOT NULL,
  remark varchar(90) NOT NULL,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_grade_system
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_login_sessions
--

DROP TABLE IF EXISTS tbl_login_sessions CASCADE;
CREATE TABLE IF NOT EXISTS tbl_login_sessions (
  session_key varchar(90) NOT NULL,
  staff integer DEFAULT NULL,
  student varchar(20) DEFAULT NULL,
  ip_address varchar(90) NOT NULL,
  PRIMARY KEY (session_key)
);
--
-- Dumping data for table tbl_login_sessions
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_school
--

DROP TABLE IF EXISTS tbl_school CASCADE;
CREATE TABLE IF NOT EXISTS tbl_school (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(100) NOT NULL,
  logo varchar(50) NOT NULL,
  result_system integer NOT NULL,
  allow_results integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_school
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_smtp
--

DROP TABLE IF EXISTS tbl_smtp CASCADE;
CREATE TABLE IF NOT EXISTS tbl_smtp (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  server varchar(255) NOT NULL,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  port varchar(255) NOT NULL,
  encryption varchar(255) NOT NULL,
  status integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_smtp
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_staff
--

DROP TABLE IF EXISTS tbl_staff CASCADE;
CREATE TABLE IF NOT EXISTS tbl_staff (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  fname varchar(20) NOT NULL,
  lname varchar(20) NOT NULL,
  gender varchar(6) NOT NULL,
  email varchar(90) NOT NULL,
  password varchar(90) NOT NULL,
  level integer NOT NULL,
  status integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_staff
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_students
--

DROP TABLE IF EXISTS tbl_students CASCADE;
CREATE TABLE IF NOT EXISTS tbl_students (
  id varchar(20) NOT NULL,
  fname varchar(70) NOT NULL,
  mname varchar(70) NOT NULL,
  lname varchar(70) NOT NULL,
  gender varchar(7) NOT NULL,
  email varchar(90) NOT NULL,
  class integer NOT NULL,
  password varchar(90) NOT NULL,
  level integer NOT NULL DEFAULT 3,
  display_image varchar(50) NOT NULL DEFAULT 'Blank',
  status integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_students
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_subjects
--

DROP TABLE IF EXISTS tbl_subjects CASCADE;
CREATE TABLE IF NOT EXISTS tbl_subjects (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(90) NOT NULL,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_subjects
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_subject_combinations
--

DROP TABLE IF EXISTS tbl_subject_combinations CASCADE;
CREATE TABLE IF NOT EXISTS tbl_subject_combinations (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  class varchar(100) NOT NULL,
  subject integer NOT NULL,
  teacher integer NOT NULL,
  reg_date timestamp NOT NULL,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_subject_combinations
--


-- --------------------------------------------------------

--
-- Table structure for table tbl_terms
--

DROP TABLE IF EXISTS tbl_terms CASCADE;
CREATE TABLE IF NOT EXISTS tbl_terms (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(90) NOT NULL,
  status integer NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);
--
-- Dumping data for table tbl_terms
--


--
-- Constraints for dumped tables
--

--
-- Constraints for table tbl_exam_results
--
ALTER TABLE tbl_exam_results
  ADD CONSTRAINT tbl_exam_results_ibfk_1 FOREIGN KEY (student) REFERENCES tbl_students (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT tbl_exam_results_ibfk_2 FOREIGN KEY (class) REFERENCES tbl_classes (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT tbl_exam_results_ibfk_3 FOREIGN KEY (subject_combination) REFERENCES tbl_subject_combinations (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT tbl_exam_results_ibfk_4 FOREIGN KEY (term) REFERENCES tbl_terms (id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table tbl_login_sessions
--
ALTER TABLE tbl_login_sessions
  ADD CONSTRAINT tbl_login_sessions_ibfk_1 FOREIGN KEY (staff) REFERENCES tbl_staff (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT tbl_login_sessions_ibfk_2 FOREIGN KEY (student) REFERENCES tbl_students (id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table tbl_students
--
ALTER TABLE tbl_students
  ADD CONSTRAINT tbl_students_ibfk_1 FOREIGN KEY (class) REFERENCES tbl_classes (id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table tbl_subject_combinations
--
ALTER TABLE tbl_subject_combinations
  ADD CONSTRAINT tbl_subject_combinations_ibfk_2 FOREIGN KEY (subject) REFERENCES tbl_subjects (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT tbl_subject_combinations_ibfk_3 FOREIGN KEY (teacher) REFERENCES tbl_staff (id) ON DELETE CASCADE ON UPDATE CASCADE;


-- Set identity sequences after inserts
SELECT setval(pg_get_serial_sequence('tbl_announcements', 'id'), COALESCE((SELECT MAX(id) FROM tbl_announcements), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_classes', 'id'), COALESCE((SELECT MAX(id) FROM tbl_classes), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_exam_results', 'id'), COALESCE((SELECT MAX(id) FROM tbl_exam_results), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_grade_system', 'id'), COALESCE((SELECT MAX(id) FROM tbl_grade_system), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_school', 'id'), COALESCE((SELECT MAX(id) FROM tbl_school), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_smtp', 'id'), COALESCE((SELECT MAX(id) FROM tbl_smtp), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_staff', 'id'), COALESCE((SELECT MAX(id) FROM tbl_staff), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_subjects', 'id'), COALESCE((SELECT MAX(id) FROM tbl_subjects), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_subject_combinations', 'id'), COALESCE((SELECT MAX(id) FROM tbl_subject_combinations), 1), true);
SELECT setval(pg_get_serial_sequence('tbl_terms', 'id'), COALESCE((SELECT MAX(id) FROM tbl_terms), 1), true);

COMMIT;

